do $$ begin create role anon nologin; exception when duplicate_object then null; end $$;
do $$ begin create role authenticated nologin; exception when duplicate_object then null; end $$;
do $$ begin create role service_role nologin; exception when duplicate_object then null; end $$;
create schema if not exists auth; create schema if not exists private;
grant usage on schema public, auth, private to anon, authenticated, service_role;
create table auth.users (id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant execute on function auth.uid() to anon, authenticated;
create table public.m_auth_user_links (auth_user_id uuid, m_uid uuid, is_primary boolean default true);
create function public.current_m_uid() returns uuid language sql stable security definer set search_path = public as $$ select m_uid from public.m_auth_user_links where auth_user_id = auth.uid() and is_primary limit 1 $$;
revoke execute on function public.current_m_uid() from public, anon;
grant execute on function public.current_m_uid() to authenticated, service_role;
create table public.org_members (org_id uuid, profile_id uuid);
create table public.network_follows (follower_m_uid uuid, followed_m_uid uuid, status text);
create table public.network_group_members (group_id uuid, m_uid uuid, state text);
create table public.creator_tracks (id uuid primary key default gen_random_uuid(), m_uid uuid, status text);
create table public.music_creator_profiles (m_uid uuid primary key, status text);
create table public.music_license_offers (id uuid primary key default gen_random_uuid(), creator_m_uid uuid, active boolean);
create table public.network_activity (id uuid primary key default gen_random_uuid(), actor_m_uid uuid, visibility text, source_org_id uuid);
create table public.network_attribution (m_uid uuid);
create table public.network_blocks (blocker_m_uid uuid);
create table public.network_bookmarks (m_uid uuid);
create table public.network_connections (requester_m_uid uuid, addressee_m_uid uuid);
create table public.network_mutes (muter_m_uid uuid);
create table public.network_post_edges (actor_m_uid uuid);
create table public.network_posts (id uuid primary key default gen_random_uuid(), author_m_uid uuid, visibility text, group_id uuid, deleted_at timestamptz, removed_at timestamptz, reply_to_id uuid);
create table public.network_profiles (m_uid uuid primary key, visibility text);
create table public.network_sessions (m_uid uuid);
create table public.network_telemetry_events (m_uid uuid);
do $$ declare t text; begin
  foreach t in array array['creator_tracks','music_creator_profiles','music_license_offers','network_activity','network_attribution','network_blocks','network_bookmarks','network_connections','network_follows','network_mutes','network_post_edges','network_posts','network_profiles','network_sessions','network_telemetry_events'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('grant select, insert, update on public.%I to anon, authenticated', t);
  end loop;
end $$;
create policy music_creator_tracks_read on public.creator_tracks for select to anon, authenticated using ((status = 'published') or (m_uid = current_m_uid()));
create policy music_creator_profiles_read on public.music_creator_profiles for select to anon, authenticated using ((status = 'active') or (m_uid = current_m_uid()));
create policy music_license_offers_read on public.music_license_offers for select to anon, authenticated using ((active = true) or (creator_m_uid = current_m_uid()));
create policy network_activity_read on public.network_activity for select using ((visibility = 'public') or (actor_m_uid = current_m_uid()));
create policy network_activity_self_insert on public.network_activity for insert with check (actor_m_uid = current_m_uid());
create policy network_attribution_self_insert on public.network_attribution for insert with check (m_uid = current_m_uid());
create policy network_blocks_self on public.network_blocks using (blocker_m_uid = current_m_uid()) with check (blocker_m_uid = current_m_uid());
create policy network_bookmarks_self on public.network_bookmarks using (m_uid = current_m_uid()) with check (m_uid = current_m_uid());
create policy network_connections_member_read on public.network_connections for select using ((requester_m_uid = current_m_uid()) or (addressee_m_uid = current_m_uid()));
create policy network_connections_self_update on public.network_connections for update using (requester_m_uid = current_m_uid()) with check (requester_m_uid = current_m_uid());
create policy network_connections_self_write on public.network_connections for insert with check (requester_m_uid = current_m_uid());
create policy network_follows_self_read on public.network_follows for select using ((follower_m_uid = current_m_uid()) or (followed_m_uid = current_m_uid()));
create policy network_follows_self_write on public.network_follows using (follower_m_uid = current_m_uid()) with check (follower_m_uid = current_m_uid());
create policy network_mutes_self on public.network_mutes using (muter_m_uid = current_m_uid()) with check (muter_m_uid = current_m_uid());
create policy network_post_edges_self_write on public.network_post_edges for insert with check (actor_m_uid = current_m_uid());
create policy action_network_posts_read on public.network_posts for select to anon, authenticated using ((deleted_at is null) and (visibility = 'public' or author_m_uid = (select current_m_uid())));
create policy network_profiles_read on public.network_profiles for select using ((m_uid = current_m_uid()) or (visibility = 'public'));
create policy network_profiles_self on public.network_profiles using (m_uid = current_m_uid()) with check (m_uid = current_m_uid());
create policy network_sessions_self_insert on public.network_sessions for insert with check (m_uid = current_m_uid());
create policy network_sessions_self_read on public.network_sessions for select using (m_uid = current_m_uid());
create policy network_telemetry_self_insert on public.network_telemetry_events for insert with check (m_uid = current_m_uid());
insert into public.creator_tracks (status) values ('published'), ('draft');
insert into public.music_creator_profiles values (gen_random_uuid(), 'active');
insert into public.network_profiles values (gen_random_uuid(), 'public'), (gen_random_uuid(), 'network');
insert into public.network_posts (visibility) values ('public');
-- for the music-reads migration
create table public.events_lean (id uuid primary key default gen_random_uuid(), at timestamptz not null default now(), name text not null, device_id text, session_id text, is_bot boolean not null default false, track text);
