/* ============================================================
   The M-Verified registry, the network's verification brain.
   Every identifier the network recognizes, every entity type it
   verifies, and which identifiers each type must present.
   Shared by verify.html (the application) and identifiers.html
   (the education page).
   ============================================================ */

window.MCC_IDENTIFIERS = {
  "ein": {
    name: "EIN",
    long: "Employer Identification Number",
    issuer: "Internal Revenue Service (IRS)",
    url: "https://www.irs.gov/businesses/small-businesses-self-employed/get-an-employer-identification-number",
    what: "The federal tax ID for a US business or nonprofit. It proves the organization exists to the IRS and is the anchor every other business identifier hangs from.",
    format: "XX-XXXXXXX",
  },
  "state-filing": {
    name: "State Filing No.",
    long: "State Business Registration Number",
    issuer: "Your state's Secretary of State (CT: business.ct.gov)",
    url: "https://business.ct.gov",
    what: "The registration number your state issued when the business was formed. It proves the entity is in good standing where it actually operates.",
    format: "Varies by state (CT: 7 to 10 digits)",
  },
  "alei": {
    name: "ALEI",
    long: "Authoritative Legal Entity Identifier",
    issuer: "State registry (CT issues these with your filing)",
    url: "https://business.ct.gov",
    what: "A structured legal-entity identifier that encodes the jurisdiction and registry record. It is the machine-readable version of your state registration.",
    format: "US-CT.BER:XXXXXXX",
  },
  "sx-rights": {
    name: "SoundExchange Rights Owner ID",
    long: "SoundExchange Rights Owner Account + SubID",
    issuer: "SoundExchange",
    url: "https://www.soundexchange.com",
    what: "Registers who owns recordings so digital-radio royalties get paid to the right party. Required to collect the rights-owner half of every spin.",
    format: "Account no. + SXXXXXXXXX SubID",
  },
  "sx-performer": {
    name: "SoundExchange Performer SubID",
    long: "SoundExchange Featured Performer Account",
    issuer: "SoundExchange",
    url: "https://www.soundexchange.com",
    what: "Registers the performer on a recording, the artist half of digital-radio royalties. Separate from the rights-owner side even when they're the same person.",
    format: "SXXXXXXXXX",
  },
  "isrc-prefix": {
    name: "ISRC Prefix",
    long: "International Standard Recording Code registrant prefix",
    issuer: "US ISRC Agency (RIAA)",
    url: "https://usisrc.org",
    what: "Your allocated prefix for coding recordings. Every track you release carries a code built from it, which is how plays get matched to owners worldwide.",
    format: "5 characters (e.g. QT6KV)",
  },
  "dpid": {
    name: "DDEX DPID",
    long: "DDEX Party Identifier",
    issuer: "DDEX (the digital supply-chain standards body)",
    url: "https://dpid.ddex.net",
    what: "Identifies your organization inside the digital music supply chain: the ID distributors, DSPs, and labels use to exchange release metadata with you.",
    format: "PA-DPIDA-XXXXXXXXXX-X",
  },
  "isni": {
    name: "ISNI",
    long: "International Standard Name Identifier",
    issuer: "ISNI International Agency",
    url: "https://isni.org",
    what: "The global name ID for people and organizations in creative work. It keeps your credits attached to YOU across every database that spells your name differently.",
    format: "16 digits (0000 0000 0000 0000)",
  },
  "charity": {
    name: "Charity Registration",
    long: "State Charitable Organization Registration",
    issuer: "State consumer-protection dept. (CT: CHR number)",
    url: "https://portal.ct.gov/dcp",
    what: "Licenses a nonprofit to solicit donations in its state. The public can look it up; it's the difference between a charity and a cash app.",
    format: "CHR.XXXXXXX (CT)",
  },
  "ueid": {
    name: "UEID",
    long: "Unique Entity ID (SAM.gov)",
    issuer: "US General Services Administration",
    url: "https://sam.gov",
    what: "The ID that lets an organization do business with the federal government. Grants, contracts, and payments all key off it.",
    format: "12 characters",
  },
  "cage": {
    name: "CAGE / NCAGE",
    long: "Commercial and Government Entity Code",
    issuer: "Defense Logistics Agency / NATO",
    url: "https://cage.dla.mil",
    what: "The facility-level code for government and defense supply chains. Paired with a UEID it clears you for federal and NATO procurement.",
    format: "5 characters",
  },
  "orcid": {
    name: "ORCID",
    long: "Open Researcher and Contributor ID",
    issuer: "ORCID (nonprofit registry)",
    url: "https://orcid.org",
    what: "The persistent ID for researchers and authors. Ties your publications, credits, and affiliations to one verified record.",
    format: "XXXX-XXXX-XXXX-XXXX",
  },
  "ssrn": {
    name: "SSRN Author ID",
    long: "Social Science Research Network Author ID",
    issuer: "SSRN (Elsevier)",
    url: "https://www.ssrn.com",
    what: "Your author record on the preprint network, where working papers and research live before formal publication.",
    format: "Numeric",
  },
  "insurance": {
    name: "Liability Insurance",
    long: "General Liability Coverage Attestation",
    issuer: "Your insurance carrier",
    url: "",
    what: "Venues and studios hosting the public carry general liability coverage. We verify a certificate of insurance before the badge is issued.",
    format: "Carrier + policy number",
  },
};

window.MCC_ENTITIES = {
  "venue": {
    label: "Studio & Venue Partner",
    tier: "org", categories: ["studios", "stages"],
    badge: "M-Verified · Venue",
    color: "#e5383b",
    desc: "Recording studios, photo studios, and event spaces that host the network's bookings.",
    required: ["ein", "state-filing", "insurance"],
    optional: ["alei", "ueid"],
  },
  "rights-owner": {
    label: "Label / Rights Owner",
    tier: "business", categories: ["music"],
    badge: "M-Verified · Rights Owner",
    color: "#d4a017",
    desc: "Labels and catalogs that own recordings and collect on them.",
    required: ["ein", "sx-rights", "isrc-prefix", "dpid"],
    optional: ["isni", "state-filing"],
  },
  "performer": {
    label: "Performer / Artist",
    tier: "creator", categories: ["music"],
    badge: "M-Verified · Performer",
    color: "#8b5cf6",
    desc: "Featured artists and session performers with registered credits.",
    required: ["isni", "sx-performer"],
    optional: ["orcid", "ein"],
  },
  "nonprofit": {
    label: "Nonprofit / Charity",
    tier: "org", categories: ["programs"],
    badge: "M-Verified · Nonprofit",
    color: "#2f9e62",
    desc: "Registered charities and community organizations in good standing.",
    required: ["ein", "charity", "state-filing"],
    optional: ["ueid"],
  },
  "federal": {
    label: "Government-Ready Contractor",
    tier: "org", categories: ["programs", "software", "studios"],
    badge: "M-Verified · Federal-Ready",
    color: "#4a7fb5",
    desc: "Organizations cleared for federal and defense work.",
    required: ["ueid", "cage", "ein", "state-filing"],
    optional: ["alei"],
  },
  "creator": {
    label: "Creator / Academic",
    tier: "creator", categories: ["video", "podcast", "writing", "art", "software", "creator", "photo", "web"],
    badge: "M-Verified · Creator",
    color: "#2aa8a0",
    desc: "Independent creators, researchers, and authors building a verified record.",
    required: ["orcid", "isni"],
    optional: ["ssrn"],
  },
};
