// Government action control surface. Drafting is medium-risk; actually filing
// is a high-risk control-plane act bound to the exact submission hash.
import { authorize, cors, db, emitEvent, json, orgBySlug, safeText, sha256Hex, verifyCaller } from "../_shared/eu-policy-os.ts";

async function load(orgId:string,id:unknown){const sid=safeText(id,80);const r=(await db(`eu_government_submissions?id=eq.${encodeURIComponent(sid)}&org_id=eq.${orgId}&select=*&limit=1`))?.[0];if(!r)throw new Error("government submission not found");return r;}
function attachments(v:unknown){return Array.isArray(v)?v.slice(0,20).map((a:any)=>({filename:safeText(a.filename||a.name,180),url:safeText(a.url,1200),mime_type:safeText(a.mime_type||a.content_type,120)})).filter((a:any)=>a.filename&&a.url):[];}
async function hashSubmission(s:any){return sha256Hex(JSON.stringify({id:s.id,initiative_id:s.initiative_id,target_id:s.target_id,docket_id:s.docket_id,publication_id:s.publication_id,submission_type:s.submission_type,title:s.title,body:s.body,attachments:s.attachments,provider:s.provider,deadline_at:s.deadline_at}));}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const caller=await verifyCaller(req);if(!caller)return json({error:"authentication required"},401);try{const org=await orgBySlug("mccluster");const body=await req.json();const action=safeText(body.action,60);
 if(action==="create"){
  const d=await authorize(caller,org.id,"policy.write");if(!d.allowed)return json({error:"policy.write permission required"},403);
  const initiative=safeText(body.initiative_id,80),title=safeText(body.title,600);if(!initiative||!title)return json({error:"initiative_id and title required"},400);
  const i=(await db(`eu_initiatives?id=eq.${encodeURIComponent(initiative)}&org_id=eq.${org.id}&select=id&limit=1`))?.[0];if(!i)return json({error:"initiative not found"},404);
  const made=(await db("eu_government_submissions",{method:"POST",body:JSON.stringify({org_id:org.id,initiative_id:initiative,target_id:safeText(body.target_id,80)||null,docket_id:safeText(body.docket_id,80)||null,publication_id:safeText(body.publication_id,80)||null,submission_type:safeText(body.submission_type,40)||"letter",title,body:safeText(body.body,100000),attachments:attachments(body.attachments),provider:safeText(body.provider,80),state:"draft",deadline_at:body.deadline_at||null,created_by:caller.authUserId})}))?.[0];
  await emitEvent({orgId:org.id,initiativeId:initiative,eventType:"government.submission.created",entityType:"eu_government_submissions",entityId:made.id,actorMUid:caller.mUid,actorUserId:caller.authUserId,data:{submission_type:made.submission_type,provider:made.provider}});return json({ok:true,submission:made});
 }
 if(action==="update"){
  const s=await load(org.id,body.submission_id);const d=await authorize(caller,org.id,"policy.write");if(!d.allowed)return json({error:"policy.write permission required"},403);if(!["draft","ready","failed"].includes(s.state))return json({error:`cannot edit submission in ${s.state}`},409);
  const patch:any={};for(const [k,max] of [["title",600],["body",100000],["provider",80]] as const)if(body[k]!==undefined)patch[k]=safeText(body[k],max);if(body.attachments!==undefined)patch.attachments=attachments(body.attachments);if(body.target_id!==undefined)patch.target_id=safeText(body.target_id,80)||null;if(body.docket_id!==undefined)patch.docket_id=safeText(body.docket_id,80)||null;if(body.deadline_at!==undefined)patch.deadline_at=body.deadline_at||null;patch.state="draft";const r=(await db(`eu_government_submissions?id=eq.${s.id}`,{method:"PATCH",body:JSON.stringify(patch)}))?.[0];return json({ok:true,submission:r});
 }
 if(action==="preflight"){
  const s=await load(org.id,body.submission_id);const d=await authorize(caller,org.id,"policy.read");if(!d.allowed)return json({error:"policy.read permission required"},403);const gaps:string[]=[];if(!s.title)gaps.push("title");if(!s.body)gaps.push("body");if(!s.provider)gaps.push("provider");if(s.provider==="regulations-gov"&&!s.docket_id)gaps.push("docket_id");const request_hash=await hashSubmission(s);return json({ok:true,ready:gaps.length===0,gaps,request_hash,state:s.state});
 }
 if(action==="submit"){
  const s=await load(org.id,body.submission_id);const requestHash=await hashSubmission(s);const decision=await authorize(caller,org.id,"government.submit",{resourceType:"eu_government_submissions",resourceId:s.id,requestHash,approvalId:safeText(body.approval_id,80)});if(!decision.allowed){await db(`eu_government_submissions?id=eq.${s.id}`,{method:"PATCH",body:JSON.stringify({state:"waiting-approval"})}).catch(()=>{});return json({ok:false,approval_required:true,reason:decision.reason,request_hash:requestHash,resource_type:"eu_government_submissions",resource_id:s.id,capability:"government.submit"},409);}
  const provider=s.provider||"manual";if(provider==="manual")return json({ok:false,manual_required:true,reason:"This target has no API provider; generate/export the packet and file it through the official portal."},409);
  const job=(await db("eu_jobs",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify({org_id:org.id,initiative_id:s.initiative_id,job_type:"government.submit",provider,action:"submit",capability:"government.submit",resource_type:"eu_government_submissions",resource_id:s.id,payload:{submission_id:s.id,comment_on_document_id:body.comment_on_document_id||null},state:"queued",approval_id:safeText(body.approval_id,80)||null,idempotency_key:`government:${s.id}:submit:${requestHash}`,priority:8})}))?.[0];await db(`eu_government_submissions?id=eq.${s.id}`,{method:"PATCH",body:JSON.stringify({state:"ready",control_approval_id:safeText(body.approval_id,80)||null})});await emitEvent({orgId:org.id,initiativeId:s.initiative_id,eventType:"government.submission.queued",entityType:"eu_government_submissions",entityId:s.id,actorMUid:caller.mUid,actorUserId:caller.authUserId,data:{provider,job_id:job?.id,request_hash:requestHash},idempotencyKey:`government:${s.id}:queued:${requestHash}`});return json({ok:true,job_id:job?.id,request_hash:requestHash});
 }
 return json({error:"unknown action"},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500);}});