(() => {
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const OFFICIAL={name:'Whip Equipped',accent:'#F04449',accent2:'#F6AD62'};
  const params=new URLSearchParams(location.search),apiBase=(params.get('api')||localStorage.getItem('we-api-base')||'https://api.mccluster.org').replace(/\/$/,'');
  const SESSION_KEY='we-renter-session';let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');
  const renterId=()=>session?.user?.id||localStorage.getItem('we-renter-id')||'demo-renter';
  let vehicles=[
    {id:'we-rental-standard',name:'Toyota Camry 2025',category:'economy',daily:44,rating:4.96,trips:218,seats:5,transmission:'Automatic',fuel:'Gas',operator:'WE Midtown Fleet',location:'Midtown · 0.8 mi',car:'#d7d7d5',theme:''},
    {id:'we-rental-suv',name:'Toyota Highlander 2025',category:'suv',daily:72,rating:4.98,trips:146,seats:7,transmission:'Automatic',fuel:'Hybrid',operator:'WE Local Partner',location:'Downtown · 1.4 mi',car:'#d0c2ad',theme:'suv'},
    {id:'we-rental-black',name:'Mercedes-Benz E-Class',category:'luxury',daily:118,rating:5,trips:91,seats:5,transmission:'Automatic',fuel:'Gas',operator:'WE Black Partner',location:'Business District · 2.1 mi',car:'#171719',theme:'dark'},
    {id:'we-rental-ev',name:'Tesla Model 3 Long Range',category:'ev',daily:83,rating:4.95,trips:173,seats:5,transmission:'Single-speed',fuel:'EV',operator:'WE Electric Fleet',location:'Central Station · 2.7 mi',car:'#e9eeee',theme:'ev'}
  ];
  const state={selected:vehicles[0],filter:'all',days:2,extras:[],protection:18,whiteLabel:false,brand:OFFICIAL.name,accent:OFFICIAL.accent,accent2:OFFICIAL.accent2,booking:null,checks:{license:false,photos:false,pickup:false},history:[]};
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
  function mixWhite(hex,ratio=.28){const v=parseInt(hex.replace('#',''),16),rgb=[(v>>16)&255,(v>>8)&255,v&255];return'#'+rgb.map(c=>Math.round(c+(255-c)*ratio).toString(16).padStart(2,'0')).join('')}
  function dates(){const start=new Date();start.setDate(start.getDate()+1);start.setHours(10,0,0,0);const end=new Date(start);end.setDate(end.getDate()+state.days);const fmt=d=>d.toLocaleDateString('en-US',{month:'short',day:'numeric'})+' · '+d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});return{start,end,startLabel:fmt(start),endLabel:fmt(end)}}
  function totals(){const base=state.selected.daily*state.days,extras=state.extras.reduce((s,x)=>s+x.price,0),protection=state.protection,taxable=base+extras+protection,tax=taxable*.07;return{base,extras,protection,tax,total:taxable+tax}}
  async function api(path,init={}){if(!apiBase)throw new Error('demo-mode');const headers={'content-type':'application/json',...(init.headers||{})};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;else{headers['x-we-user-id']=renterId();headers['x-we-role']='renter'}const res=await fetch(apiBase+path,{...init,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'API error');return data}
  function modal(id,html){let m=$('#'+id);if(m)m.remove();m=document.createElement('div');m.id=id;m.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.67);display:grid;place-items:end center;padding:16px;backdrop-filter:blur(9px)';m.innerHTML=`<div style="width:min(540px,100%);background:#fff;border-radius:28px;padding:25px;box-shadow:0 20px 70px #0006">${html}</div>`;document.body.appendChild(m);return m}
  async function ensureAuth(){if(!apiBase)return true;if(session?.access_token){try{await api('/api/auth/me');return true}catch{session=null;localStorage.removeItem(SESSION_KEY)}}const m=modal('renterAuth',`<div style="display:flex;align-items:center;gap:12px"><img src="assets/we-icon.png" style="width:48px;height:48px"><div><strong style="font-size:22px">WE Rentals</strong><small style="display:block;color:#777">Sign in before reserving a vehicle</small></div></div><div style="display:flex;background:#eee;padding:4px;border-radius:12px;margin:18px 0"><button data-auth="login" style="flex:1;padding:10px;border:0;border-radius:9px;background:#fff;font-weight:800">Sign in</button><button data-auth="signup" style="flex:1;padding:10px;border:0;background:transparent;font-weight:800">Create account</button></div><form id="renterAuthForm" style="display:grid;gap:12px"><input id="renterEmail" type="email" required placeholder="Email" style="padding:15px;border:1px solid #ddd;border-radius:13px"><input id="renterPassword" type="password" minlength="8" required placeholder="Password" style="padding:15px;border:1px solid #ddd;border-radius:13px"><button style="padding:15px;border:0;border-radius:13px;background:linear-gradient(135deg,#F6AD62,#F04449);color:#fff;font-weight:900">Continue</button><small id="renterAuthError" style="color:#a22"></small></form>`);let mode='login';$$('[data-auth]',m).forEach(b=>b.onclick=()=>{mode=b.dataset.auth;$$('[data-auth]',m).forEach(x=>x.style.background=x===b?'#fff':'transparent')});$('#renterAuthForm',m).onsubmit=async e=>{e.preventDefault();try{const data=await api(mode==='login'?'/api/auth/login':'/api/auth/signup',{method:'POST',body:JSON.stringify({email:$('#renterEmail',m).value,password:$('#renterPassword',m).value,data:{product:'rentals'}})});if(data.access_token){session={access_token:data.access_token,refresh_token:data.refresh_token,user:data.user};localStorage.setItem(SESSION_KEY,JSON.stringify(session));m.remove()}else $('#renterAuthError',m).textContent='Account created. Confirm your email if required, then sign in.'}catch(err){$('#renterAuthError',m).textContent=err.message}};return false}
  async function loadInventory(){if(!apiBase)return;try{const data=await api('/api/rentals/vehicles?tenant=whip-equipped');if(data.vehicles?.length){vehicles=data.vehicles.map(v=>({id:v.id,name:v.name,category:v.category,daily:Number(v.daily_rate_cents)/100,rating:Number(v.rating),trips:v.rental_count,seats:v.seats,transmission:v.transmission,fuel:v.fuel_type,operator:v.operator_name,location:v.location_label,car:v.color_hex||'#222',theme:v.category==='luxury'?'dark':v.category==='suv'?'suv':v.category==='ev'?'ev':''}));state.selected=vehicles[0]}}catch(e){console.warn('WE inventory fallback active',e)}}
  function show(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View')?.classList.add('active');window.scrollTo({top:0,behavior:'instant'});$('.sticky-price')?.toggleAttribute('hidden',name!=='details');$$('.bottom-nav button[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name))}
  function applyCar(el,v){if(!el)return;el.className=el.className.replace(/\s(?:dark|suv|ev)\b/g,'');if(v.theme)el.classList.add(v.theme);el.style.setProperty('--car',v.car);if(!el.innerHTML)el.innerHTML='<span></span>'}
  function renderVehicles(){const list=state.filter==='all'?vehicles:vehicles.filter(v=>v.category===state.filter);$('#vehicleGrid').innerHTML=list.map(v=>`<button class="vehicle-card" data-id="${v.id}"><div class="vehicle-art ${v.theme}"><div class="car-shape" style="--car:${v.car}"><span></span></div></div><div class="vehicle-card-body"><div class="vehicle-card-head"><div><span class="eyebrow">${v.operator}</span><h3>${v.name}</h3></div><div class="rate">${money(v.daily)}<small>/day</small></div></div><div class="vehicle-meta"><span>★ ${v.rating}</span><span>${v.seats} seats</span><span>${v.transmission}</span><span>${v.fuel}</span></div><div class="vehicle-footer"><small>${v.location} · ${v.trips} rentals</small><strong>View car →</strong></div></div></button>`).join('');$$('.vehicle-card').forEach(card=>card.onclick=()=>openDetails(card.dataset.id))}
  function openDetails(id){state.selected=vehicles.find(v=>v.id===id)||vehicles[0];const v=state.selected,d=dates(),t=totals();$('#vehicleHero').className=`vehicle-hero ${v.theme}`;applyCar($('#heroCar'),v);$('#detailOperator').textContent=v.operator.toUpperCase();$('#detailName').textContent=v.name;$('#detailRating').textContent=`★ ${v.rating}`;$('#detailTrips').textContent=`${v.trips} rentals`;$('#detailDates').textContent=`${d.startLabel} → ${d.endLabel}`;$('#detailLocation').textContent=v.location;$('#featureStrip').innerHTML=`<span>${v.seats} seats</span><span>${v.transmission}</span><span>${v.fuel}</span><span>200 mi/day</span>`;$('#detailDaily').textContent=`${money(v.daily)}/day`;$('#detailEstimate').textContent=`${money(t.total)} estimated total`;show('details')}
  function renderCheckout(){const v=state.selected,d=dates(),t=totals();applyCar($('#checkoutCar'),v);applyCar($('#bookedCar'),v);applyCar($('#activeCar'),v);$('#checkoutName').textContent=v.name;$('#checkoutDates').textContent=`${d.startLabel} → ${d.endLabel}`;$('#baseRateLabel').textContent=`${money(v.daily)}/day × ${state.days} days`;$('#baseRateValue').textContent=money(t.base);$('#protectionValue').textContent=money(t.protection);$('#taxValue').textContent=money(t.tax);$('#checkoutTotal').textContent=money(t.total);$('#extrasLabel').textContent=state.extras.length?`${state.extras.length} selected · ${money(t.extras)}`:'None selected'}
  function syncBooked(){const v=state.selected,d=dates(),t=totals();$('#bookedName').textContent=v.name;$('#bookedDates').textContent=`${d.startLabel} → ${d.endLabel}`;$('#bookedLocation').textContent=v.location;$('#activeName').textContent=v.name;$('#activeDue').textContent=`Return ${d.endLabel}`;$('#activeLocation').textContent=v.location;$('#activeOperator').textContent=v.operator;$('#finalVehicle').textContent=v.name;$('#finalTotal').textContent=money((state.booking?.total_cents??Math.round(t.total*100))/100);$('#finalPaymentStatus').textContent=state.booking?.payment_status==='paid'?'Paid securely':'Payment recorded'}
  function paymentReturnUrl(status,bookingId){const u=new URL(location.href);u.searchParams.delete('rental_payment');u.searchParams.delete('booking_id');u.searchParams.set('rental_payment',status);u.searchParams.set('booking_id',bookingId);if(apiBase)u.searchParams.set('api',apiBase);return u.toString()}
  function setPaymentStatus(message){const el=$('#paymentStatus');if(!el)return;el.hidden=!message;el.textContent=message||''}
  async function createBooking(){if(!(await ensureAuth()))return;const button=$('#bookButton');button.disabled=true;button.textContent='Creating reservation…';setPaymentStatus('');const v=state.selected,d=dates(),t=totals(),payload={tenant_slug:'whip-equipped',renter_id:renterId(),vehicle_id:v.id,start_at:d.start.toISOString(),end_at:d.end.toISOString(),pickup_label:v.location,rental_days:state.days,extras_cents:Math.round(t.extras*100),protection_cents:Math.round(t.protection*100),tax_cents:Math.round(t.tax*100)};try{if(!apiBase)throw new Error('demo-mode');state.booking=(await api('/api/rentals/bookings',{method:'POST',body:JSON.stringify(payload)})).booking;localStorage.setItem('we-current-rental-booking',state.booking.id);button.textContent='Opening secure payment…';const checkout=await api(`/api/rentals/bookings/${encodeURIComponent(state.booking.id)}/checkout`,{method:'POST',body:JSON.stringify({success_url:paymentReturnUrl('success',state.booking.id),cancel_url:paymentReturnUrl('cancel',state.booking.id)})});if(!checkout.checkout_url)throw new Error('Payment checkout URL was not returned');location.assign(checkout.checkout_url);return}catch(error){if(error.message==='demo-mode'){state.booking={id:'demo-rental-'+Date.now(),status:'CHECKIN_REQUIRED',payment_status:'paid',platform_fee_cents:Math.round(t.total*(state.whiteLabel?0:.03)*100),total_cents:Math.round(t.total*100),...payload};state.checks={license:false,photos:false,pickup:false};updateChecks();syncBooked();show('booked')}else{console.error(error);setPaymentStatus(error.message||'Unable to start secure payment.')}}finally{button.disabled=false;button.textContent='Continue to secure payment'}}
  async function reconcileReturnedPayment(){if(!apiBase)return false;const status=params.get('rental_payment'),bookingId=params.get('booking_id')||localStorage.getItem('we-current-rental-booking');if(!status||!bookingId)return false;if(!session?.access_token){await ensureAuth();return true}if(status==='cancel'){setPaymentStatus('Payment was canceled. Your vehicle is not ready for pickup until payment completes.');show('checkout');return true}setPaymentStatus('Confirming payment…');for(let attempt=0;attempt<10;attempt++){try{const data=await api(`/api/rentals/bookings/${encodeURIComponent(bookingId)}`);state.booking=data.booking;if(data.vehicle){const match=vehicles.find(v=>v.id===data.vehicle.id);if(match)state.selected=match}if(state.booking?.payment_status==='paid'){localStorage.setItem('we-current-rental-booking',state.booking.id);state.checks={license:Boolean(state.booking.license_verified),photos:Boolean(state.booking.pretrip_photos_complete),pickup:Boolean(state.booking.pickup_instructions_seen)};updateChecks();syncBooked();show('booked');setPaymentStatus('');return true}}catch(e){console.warn('Payment reconciliation retry',e)}await new Promise(r=>setTimeout(r,1200))}setPaymentStatus('Payment is still processing. Refresh Trips in a moment; the vehicle will not be released until Stripe confirms payment.');show('checkout');return true}
  async function rentalStatus(status){if(!state.booking)return;if(!apiBase){state.booking.status=status;return}const data=await api(`/api/rentals/bookings/${encodeURIComponent(state.booking.id)}/status`,{method:'PATCH',body:JSON.stringify({status})});if(data.booking)state.booking=data.booking}
  async function checkinField(field){if(!state.booking||!apiBase)return;try{const data=await api(`/api/rentals/bookings/${encodeURIComponent(state.booking.id)}/checkin`,{method:'PATCH',body:JSON.stringify({[field]:true})});if(data.booking)state.booking=data.booking}catch(e){console.warn(e)}}
  async function syncReturn(){if(!state.booking||!apiBase)return;const data=await api(`/api/rentals/bookings/${encodeURIComponent(state.booking.id)}/return`,{method:'PATCH',body:JSON.stringify({return_photos_complete:true,fuel_return_confirmed:true})});if(data.booking)state.booking=data.booking}
  function updateChecks(){[['license','licenseCheck','licenseStatus','License verified'],['photos','photosCheck','photosStatus','Condition photos saved'],['pickup','pickupCheck','pickupStatus','Pickup instructions unlocked']].forEach(([k,id,status,label])=>{$('#'+id)?.classList.toggle('done',state.checks[k]);if(state.checks[k]&&$('#'+status))$('#'+status).textContent=label});const ready=Object.values(state.checks).every(Boolean);if($('#startRental'))$('#startRental').disabled=!ready;if(ready&&!apiBase&&state.booking)state.booking.status='READY_FOR_PICKUP'}
  function renderHistory(){if(!state.history.length)return;$('#tripHistory').innerHTML=state.history.map(h=>`<div class="history-card"><div><strong>${h.vehicle}</strong><small>${h.dates}</small></div><div><strong>${h.total}</strong><small>Completed</small></div></div>`).join('')}
  function applyBrand(){state.whiteLabel=$('#whiteLabelToggle').checked;const name=($('#brandInput').value||OFFICIAL.name).trim(),accent=$('#accentInput').value||OFFICIAL.accent;state.brand=state.whiteLabel?name:OFFICIAL.name;state.accent=state.whiteLabel?accent:OFFICIAL.accent;state.accent2=state.whiteLabel?mixWhite(accent):OFFICIAL.accent2;document.documentElement.style.setProperty('--accent',state.accent);document.documentElement.style.setProperty('--accent2',state.accent2);$('#brandName').textContent=state.brand;$('#brandSubline').textContent=state.whiteLabel?'RENTALS · WHITE LABEL':'RENTALS · IN THIS TOGETHER';$('#brandIcon').style.display=state.whiteLabel?'none':'';localStorage.setItem('we-rental-brand',JSON.stringify({name:state.brand,accent:state.accent,whiteLabel:state.whiteLabel}));if($('#checkoutView').classList.contains('active'))renderCheckout();$('#brandDrawer').classList.remove('open')}
  function hydrateBrand(){const p=new URLSearchParams(location.search),saved=JSON.parse(localStorage.getItem('we-rental-brand')||'null'),white=p.get('whiteLabel')==='1'||saved?.whiteLabel;$('#whiteLabelToggle').checked=!!white;if(white){$('#brandInput').value=p.get('brand')||saved?.name||'Your Brand';const a=p.get('accent')||saved?.accent;if(a&&/^#[0-9a-f]{6}$/i.test(a))$('#accentInput').value=a}applyBrand()}
  function bind(){$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderVehicles()});$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#continueCheckout').onclick=()=>{renderCheckout();show('checkout')};$('#extrasButton').onclick=()=>show('extras');$('#saveExtras').onclick=()=>{state.extras=$$('[data-extra]:checked').map(x=>({id:x.dataset.extra,price:Number(x.dataset.price)}));renderCheckout();show('checkout')};$('#bookButton').onclick=createBooking;$('#licenseCheck').onclick=async()=>{state.checks.license=true;await checkinField('license_verified');updateChecks()};$('#photosCheck').onclick=async()=>{state.checks.photos=true;await checkinField('pretrip_photos_complete');updateChecks()};$('#pickupCheck').onclick=async()=>{state.checks.pickup=true;await checkinField('pickup_instructions_seen');updateChecks()};$('#startRental').onclick=async()=>{try{await rentalStatus('ACTIVE');show('active')}catch(e){alert(e.message||'Rental cannot start yet.')}};$('#beginReturn').onclick=async()=>{try{await rentalStatus('RETURN_DUE');show('return')}catch(e){alert(e.message||'Unable to begin return.')}};$$('.return-check').forEach(c=>c.onchange=()=>$('#completeReturn').disabled=!$$('.return-check').every(x=>x.checked));$('#completeReturn').onclick=async()=>{try{await syncReturn();await rentalStatus('COMPLETED')}catch(e){alert(e.message||'Unable to complete return.');return}const d=dates(),t=totals();state.history.unshift({vehicle:state.selected.name,dates:`${d.startLabel} → ${d.endLabel}`,total:money((state.booking?.total_cents??Math.round(t.total*100))/100)});renderHistory();syncBooked();show('complete')};$('#bookAnother').onclick=()=>{state.checks={license:false,photos:false,pickup:false};$$('.return-check').forEach(x=>x.checked=false);$('#completeReturn').disabled=true;updateChecks();show('discover')};$$('#stars button').forEach((s,i,arr)=>s.onclick=()=>arr.forEach((x,j)=>x.classList.toggle('active',j<=i)));$$('.bottom-nav [data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));$('#moreNav').onclick=()=>$('#brandDrawer').classList.add('open');$('#brandButton').onclick=()=>$('#brandDrawer').classList.add('open');$('#closeBrand').onclick=()=>$('#brandDrawer').classList.remove('open');$('#applyBrand').onclick=applyBrand;$('#searchBar').onclick=()=>{$('#searchBar strong').textContent='Current area';$('#searchBar small').textContent='Showing vehicles near you'};$('#mapToggle').onclick=()=>{$('#mapToggle').textContent=$('#mapToggle').textContent==='Map'?'List':'Map'}}
  document.addEventListener('DOMContentLoaded',async()=>{const d=dates();$('#startDateLabel').textContent=d.startLabel;$('#endDateLabel').textContent=d.endLabel;await loadInventory();renderVehicles();bind();hydrateBrand();updateChecks();const handled=await reconcileReturnedPayment();if(!handled)show('discover');setTimeout(()=>$('#splash').classList.add('hide'),800);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
})();