// Create lineage-tracked communication derivatives from an approved/publication.
// This function never publishes social content. It may prepare an existing
// McCluster social_campaign + variant; the hardened social subsystem owns queue/publish.
import { authorize, cors, db, emitEvent, json, orgBySlug, safeText, verifyCaller } from "../_shared/eu-policy-os.ts";

async function publication(orgId:string,id:unknown){const sid=safeText(id,80);const p=(await db(`eu_publications?id=eq.${encodeURIComponent(sid)}&org_id=eq.${orgId}&select=*&limit=1`))?.[0];if(!p)throw new Error("publication not found");return p;}
function copy(p:any,kind:string){const cite=`${p.stable_id}${p.doi?` · DOI ${p.doi}`:""}`;const url=p.canonical_url||"";switch(kind){case"executive-summary":return `${p.title}\n\n${p.abstract}\n\nRead the canonical Equity Uprise record: ${url}\n${cite}`;case"linkedin":return `${p.title}\n\n${p.abstract}\n\nFull research record, evidence, citation exports, and version history: ${url}\n\n${cite}`;case"tiktok-script":return `HOOK: ${p.title}\n\nWHAT CHANGED: ${p.abstract}\n\nWHY IT MATTERS: Explain the concrete policy stakes in plain language, using only claims supported by the source publication.\n\nCTA: Read the full Equity Uprise record at ${url}.\n\nSOURCE: ${cite}`;case"youtube-briefing":return `TITLE: ${p.title}\n\nOPEN\nThis briefing is based on Equity Uprise publication ${cite}.\n\nSUMMARY\n${p.abstract}\n\nBODY\nWalk through the findings, evidence, competing considerations, and recommendations from the canonical publication. Do not introduce unsupported factual claims.\n\nSOURCE\n${url}`;case"press-release":return `FOR RELEASE\n\nEquity Uprise publishes: ${p.title}\n\n${p.abstract}\n\nThe complete research record, including citation metadata and version history, is available at ${url}.\n\nReference: ${cite}`;default:return `${p.title}\n\n${p.abstract}\n\n${url}\n${cite}`;}}
async function makeArtifact(org:any,caller:any,p:any,kind:string){const artifactType=kind==="press-release"?"press-release":kind==="executive-summary"?"policy-brief":"social-copy";const title=`${p.stable_id} · ${kind}`;const existing=(await db(`eu_artifacts?org_id=eq.${org.id}&parent_artifact_id=eq.${p.artifact_id}&artifact_type=eq.${artifactType}&metadata->>kind=eq.${encodeURIComponent(kind)}&select=*&limit=1`))?.[0];if(existing)return existing;const a=(await db("eu_artifacts",{method:"POST",body:JSON.stringify({org_id:org.id,initiative_id:p.initiative_id,research_project_id:p.research_project_id,parent_artifact_id:p.artifact_id,artifact_type:artifactType,title,status:"draft",metadata:{kind,body:copy(p,kind),source_publication_id:p.id,source_stable_id:p.stable_id,source_version:p.current_version},lineage:{derived_from:p.artifact_id,publication_id:p.id,version:p.current_version},created_by_m_uid:caller.mUid})}))?.[0];await db("eu_artifact_dependencies",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify({source_artifact_id:p.artifact_id,dependent_artifact_id:a.id,dependency_type:"promotes",metadata:{kind,publication_version:p.current_version}})}).catch(()=>{});await emitEvent({orgId:org.id,initiativeId:p.initiative_id,eventType:"artifact.derivative.created",entityType:"eu_artifacts",entityId:a.id,actorMUid:caller.mUid,actorUserId:caller.authUserId,data:{kind,source_publication_id:p.id}});return a;}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const caller=await verifyCaller(req);if(!caller)return json({error:"authentication required"},401);try{const org=await orgBySlug("mccluster");const body=await req.json();const action=safeText(body.action,60);const p=await publication(org.id,body.publication_id);const auth=await authorize(caller,org.id,"research.write");if(!auth.allowed)return json({error:"research.write permission required"},403);
 if(action==="generate") {const kinds=(Array.isArray(body.kinds)?body.kinds:["executive-summary","linkedin","tiktok-script","youtube-briefing","press-release"]).slice(0,20).map((x:any)=>safeText(x,60));const out=[];for(const k of kinds)out.push(await makeArtifact(org,caller,p,k));return json({ok:true,artifacts:out});}
 if(action==="prepare-social") {const platform=safeText(body.platform,40);if(!["linkedin","tiktok","youtube","instagram","threads","x"].includes(platform))return json({error:"unsupported platform"},400);const sa=body.account_id?(await db(`social_accounts?id=eq.${encodeURIComponent(String(body.account_id))}&org_id=eq.${org.id}&status=eq.connected&select=*&limit=1`))?.[0]:(await db(`social_accounts?org_id=eq.${org.id}&platform=eq.${encodeURIComponent(platform)}&status=eq.connected&select=*&limit=1`))?.[0];if(!sa)return json({error:`no connected ${platform} account`},409);const artifact=await makeArtifact(org,caller,p,platform==="tiktok"?"tiktok-script":platform==="youtube"?"youtube-briefing":"linkedin");const campaign=(await db("social_campaigns",{method:"POST",body:JSON.stringify({org_id:org.id,account_id:sa.id,name:`${p.stable_id} · ${platform}`,objective:"policy-education",status:"draft",created_by:caller.authUserId,settings:{equity_uprise:true,publication_id:p.id,artifact_id:artifact.id,canonical_url:p.canonical_url}})}))?.[0];const variant=(await db("social_variants",{method:"POST",body:JSON.stringify({org_id:org.id,campaign_id:campaign.id,variant_key:"canonical",hypothesis:"Canonical research-derived policy education",hook:p.title,caption:artifact.metadata?.body||copy(p,"linkedin"),hashtags:[],status:"planned",metadata:{equity_uprise:true,publication_id:p.id,artifact_id:artifact.id,source_version:p.current_version}})}))?.[0];await db(`eu_artifacts?id=eq.${artifact.id}`,{method:"PATCH",body:JSON.stringify({metadata:{...(artifact.metadata||{}),social_campaign_id:campaign.id,social_variant_id:variant.id,platform}})});return json({ok:true,campaign_id:campaign.id,variant_id:variant.id,artifact_id:artifact.id,note:"Prepared only. Existing McCluster social approval/publish controls still govern external posting."});}
 return json({error:"unknown action"},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500);}});