(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const OFFICIAL_BRAND='Whip Equipped',OFFICIAL_CORAL='#F04449',OFFICIAL_ORANGE='#F6AD62',BRAND_ICON='assets/we-icon.svg';
  const API_BASE=(new URLSearchParams(location.search).get('api')||localStorage.getItem('we-api-base')||'https://api.mccluster.org').replace(/\/$/,'');
  const SESSION_KEY='we-rider-session';
  let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');
  const RIDER_ID=()=>session?.user?.id||localStorage.getItem('we-rider-id')||'demo-rider';
  const state={current:'home',destination:null,miles:4.8,minutes:14,selectedRide:null,whiteLabel:false,brand:OFFICIAL_BRAND,accent:OFFICIAL_CORAL,accent2:OFFICIAL_ORANGE,map:null,route:null,destinationMarker:null,pickupMarker:null,driverMarkers:[],activeRide:null,pollTimer:null,stripe:null,paymentElement:null};
  const rideTiers=[{id:'standard',name:'Standard',subtitle:'Reliable ride · 1–4 riders',eta:3,multiplier:1,icon:'sedan'},{id:'comfort',name:'Comfort',subtitle:'Newer car · extra room',eta:5,multiplier:1.28,icon:'comfort'},{id:'xl',name:'XL',subtitle:'Room for the crew · up to 6',eta:7,multiplier:1.58,icon:'suv'},{id:'black',name:'Black',subtitle:'Premium vehicle · top-rated driver',eta:9,multiplier:2.18,icon:'black'}];
  const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0),cents=v=>Math.round((Number(v)||0)*100);
  async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;else{headers['x-we-user-id']=RIDER_ID();headers['x-we-role']='rider'}const res=await fetch(`${API_BASE}${path}`,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||data.error||`HTTP ${res.status}`);return data}
  function tierName(t){if(!state.whiteLabel)return`WE ${t.name}`;const b=state.brand.length>16?state.brand.split(' ')[0]:state.brand;return`${b} ${t.name}`}
  function mixWithWhite(hex,ratio=.35){const n=parseInt(hex.replace('#',''),16),rgb=[(n>>16)&255,(n>>8)&255,n&255].map(c=>Math.round(c+(255-c)*ratio).toString(16).padStart(2,'0'));return`#${rgb.join('')}`}
  function baseMarketFare(miles,minutes){return Math.max(8.5,(2.4+miles*1.62+minutes*.31+2.15)*1.06)}
  function quoteForTier(t){return Math.round(baseMarketFare(state.miles,state.minutes)*t.multiplier*100)/100}
  const processingEstimate=a=>a*.029+.30,platformFee=a=>state.whiteLabel?0:a*.03,operatorNet=a=>a-processingEstimate(a)-platformFee(a);
  function setState(name){state.current=name;$$('.state').forEach(x=>x.classList.remove('active'));$(`#${name}State`)?.classList.add('active');const sheet=$('#rideSheet');if(sheet){sheet.scrollTop=0;sheet.style.maxHeight=['search','options'].includes(name)?'72dvh':'';if(name==='matching')sheet.style.maxHeight='45dvh';if(name==='pickup')sheet.style.maxHeight='58dvh';if(name==='complete')sheet.style.maxHeight='60dvh'}}
  function initMap(){if(!window.L)return;const start=[40.7414,-73.9896];state.map=L.map('map',{zoomControl:false,attributionControl:true}).setView(start,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(state.map);const pickupIcon=L.divIcon({className:'',html:'<div class="custom-marker"></div>',iconSize:[28,28],iconAnchor:[14,28]});state.pickupMarker=L.marker(start,{icon:pickupIcon}).addTo(state.map);[[.009,.012],[-.006,.014],[.003,-.014],[-.011,-.007],[.013,-.006]].forEach(([lat,lng])=>{const icon=L.divIcon({className:'',html:'<div class="driver-pin"></div>',iconSize:[26,16],iconAnchor:[13,8]});state.driverMarkers.push(L.marker([start[0]+lat,start[1]+lng],{icon}).addTo(state.map))})}
  function drawRoute(){if(!state.map||!state.pickupMarker)return;const start=state.pickupMarker.getLatLng(),latDelta=Math.min(.095,state.miles*.0062),lngDelta=Math.min(.12,state.miles*.0077),end=L.latLng(start.lat+latDelta,start.lng+lngDelta),mid=L.latLng(start.lat+latDelta*.48,start.lng+lngDelta*.37);if(state.route)state.map.removeLayer(state.route);if(state.destinationMarker)state.map.removeLayer(state.destinationMarker);state.route=L.polyline([start,mid,end],{color:state.accent,weight:5,opacity:.95,lineCap:'round'}).addTo(state.map);const destIcon=L.divIcon({className:'',html:'<div class="custom-marker" style="background:#111111"></div>',iconSize:[28,28],iconAnchor:[14,28]});state.destinationMarker=L.marker(end,{icon:destIcon}).addTo(state.map);state.map.fitBounds(state.route.getBounds().pad(.32),{animate:true})}
  function renderRideOptions(){const root=$('#rideOptions');if(!root)return;root.innerHTML=rideTiers.map(t=>{const p=quoteForTier(t),net=operatorNet(p);return`<button class="ride-option" data-tier="${t.id}" data-price="${p}"><span class="car-visual ${t.icon}"></span><span class="ride-option-copy"><strong>${tierName(t)}</strong><small>${t.eta} min away · ${t.subtitle}</small><em>Local operator est. net ${money(net)}*</em></span><span class="ride-price"><strong>${money(p)}</strong><small>upfront</small></span></button>`}).join('');$$('.ride-option',root).forEach(btn=>btn.addEventListener('click',()=>{$$('.ride-option',root).forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');const t=rideTiers.find(x=>x.id===btn.dataset.tier);state.selectedRide={...t,price:Number(btn.dataset.price),displayName:tierName(t)};$('#confirmRide').textContent=`Request ${state.selectedRide.displayName} · ${money(state.selectedRide.price)}`;$('#confirmRide').disabled=false}));state.selectedRide=null;$('#confirmRide').textContent='Choose a ride';$('#confirmRide').disabled=true}
  function chooseDestination(place,miles=4.8,minutes=14){state.destination=place;state.miles=Number(miles);state.minutes=Number(minutes);$('#dropoffInput').value=place;$('#routeTitle').textContent=`To ${place}`;$('#routeMeta').textContent=`${state.miles.toFixed(1)} mi · ~${state.minutes} min`;drawRoute();renderRideOptions();setState('options')}
  function openOperator(){$('#operatorDrawer').classList.add('open');$('#operatorDrawer').setAttribute('aria-hidden','false')}function closeOperator(){$('#operatorDrawer').classList.remove('open');$('#operatorDrawer').setAttribute('aria-hidden','true')}
  function syncBrandChrome(){const app=$('#app');app.classList.toggle('white-label-mode',state.whiteLabel);$('#brandName').textContent=state.brand;$('#brandMode').textContent=state.whiteLabel?'WHITE LABEL PREVIEW':'IN THIS TOGETHER · NETWORK';$('#completeThanks').textContent=`Thanks for riding ${state.brand}.`;const mark=$('#brandMark');if(state.whiteLabel){mark.innerHTML=`<span>${state.brand.slice(0,1).toUpperCase()}</span>`;mark.style.background='var(--brand-gradient)'}else{mark.innerHTML=`<img src="${BRAND_ICON}" alt="Whip Equipped" />`;mark.style.background='#050505'}$$('.home-brand-kicker,.map-brand-watermark').forEach(el=>el.style.display=state.whiteLabel?'none':'')}
  function applyBrand(){const brand=($('#brandInput').value||OFFICIAL_BRAND).trim(),accent=$('#accentInput').value||OFFICIAL_CORAL;state.brand=state.whiteLabel?brand:OFFICIAL_BRAND;state.accent=state.whiteLabel?accent:OFFICIAL_CORAL;state.accent2=state.whiteLabel?mixWithWhite(state.accent,.28):OFFICIAL_ORANGE;document.documentElement.style.setProperty('--accent',state.accent);document.documentElement.style.setProperty('--accent-2',state.accent2);syncBrandChrome();localStorage.setItem('we-brand-preview',JSON.stringify({brand:state.brand,accent:state.accent,whiteLabel:state.whiteLabel}));if(state.route)state.route.setStyle({color:state.accent});renderRideOptions()}
  function setWhiteLabel(enabled){state.whiteLabel=enabled;if(!enabled){state.brand=OFFICIAL_BRAND;state.accent=OFFICIAL_CORAL;state.accent2=OFFICIAL_ORANGE;$('#brandInput').value=OFFICIAL_BRAND;$('#accentInput').value=OFFICIAL_CORAL;document.documentElement.style.setProperty('--accent',OFFICIAL_CORAL);document.documentElement.style.setProperty('--accent-2',OFFICIAL_ORANGE)}$('#platformFeeDemo').textContent=enabled?'$0.00':'$0.74';$('#operatorNetDemo').textContent=enabled?'≈ $23.78':'≈ $23.04';$('#upgradeButton').textContent=enabled?'White label on':'Preview';syncBrandChrome();renderRideOptions()}
  function hydrateBrand(){const p=new URLSearchParams(location.search),saved=JSON.parse(localStorage.getItem('we-brand-preview')||'null'),wl=p.get('whiteLabel')==='1'||saved?.whiteLabel===true;if(wl){setWhiteLabel(true);$('#brandInput').value=p.get('brand')||saved?.brand||'Your Brand';const a=p.get('accent')||saved?.accent||OFFICIAL_CORAL;if(/^#[0-9a-f]{6}$/i.test(a))$('#accentInput').value=a;applyBrand()}else{setWhiteLabel(false);applyBrand()}}

  function modalBase(id){let m=$('#'+id);if(m)return m;m=document.createElement('div');m.id=id;m.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.62);z-index:9999;display:grid;place-items:end center;padding:16px;backdrop-filter:blur(8px)';document.body.appendChild(m);return m}
  function authModal(){const m=modalBase('weAuthModal');m.innerHTML=`<div style="width:min(520px,100%);background:#fff;border-radius:28px;padding:26px;box-shadow:0 20px 70px #0006"><div style="display:flex;gap:12px;align-items:center;margin-bottom:18px"><img src="${BRAND_ICON}" style="width:46px;height:46px"><div><strong style="font-size:22px">Ride with WE</strong><small style="display:block;color:#777">Sign in before requesting a ride</small></div></div><div style="display:flex;background:#eee;padding:4px;border-radius:12px;margin-bottom:16px"><button data-mode="login" style="flex:1;padding:10px;border:0;border-radius:9px;background:#fff;font-weight:800">Sign in</button><button data-mode="signup" style="flex:1;padding:10px;border:0;background:transparent;font-weight:800">Create account</button></div><form id="weAuthForm" style="display:grid;gap:12px"><input id="weEmail" type="email" required placeholder="Email" style="padding:15px;border:1px solid #ddd;border-radius:13px"><input id="wePassword" type="password" minlength="8" required placeholder="Password" style="padding:15px;border:1px solid #ddd;border-radius:13px"><button style="padding:15px;border:0;border-radius:13px;background:linear-gradient(135deg,#F6AD62,#F04449);color:white;font-weight:900">Continue</button><small id="weAuthError" style="color:#a22"></small></form></div>`;let mode='login';$$('[data-mode]',m).forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]',m).forEach(x=>x.style.background=x===b?'#fff':'transparent')});$('#weAuthForm',m).onsubmit=async e=>{e.preventDefault();const err=$('#weAuthError',m);err.textContent='';try{const data=await api(mode==='login'?'/api/auth/login':'/api/auth/signup',{method:'POST',body:JSON.stringify({email:$('#weEmail',m).value,password:$('#wePassword',m).value,data:{product:'rider'}})});if(data.access_token){session={access_token:data.access_token,refresh_token:data.refresh_token,user:data.user};localStorage.setItem(SESSION_KEY,JSON.stringify(session));m.remove()}else err.textContent='Account created. Confirm your email if required, then sign in.'}catch(x){err.textContent=x.message}};return m}
  async function ensureAuth(){if(session?.access_token){try{await api('/api/auth/me');return true}catch{session=null;localStorage.removeItem(SESSION_KEY)}}authModal();return false}

  function loadStripeJs(){return new Promise((resolve,reject)=>{if(window.Stripe)return resolve();const s=document.createElement('script');s.src='https://js.stripe.com/v3/';s.onload=resolve;s.onerror=()=>reject(new Error('Could not load secure payment form'));document.head.appendChild(s)})}
  async function collectRidePayment(ride){
    const p=await api(`/api/rides/${ride.id}/payment-intent`,{method:'POST',body:'{}'});if(!p.client_secret)return true;
    await loadStripeJs();state.stripe=Stripe(p.publishable_key,{stripeAccount:p.connected_account_id});const elements=state.stripe.elements({clientSecret:p.client_secret,appearance:{theme:'stripe',variables:{colorPrimary:state.accent,borderRadius:'12px'}}});
    const modal=modalBase('wePaymentModal');modal.innerHTML=`<div style="width:min(560px,100%);background:#fff;border-radius:28px;padding:25px;box-shadow:0 20px 70px #0006"><div style="display:flex;justify-content:space-between;gap:14px;align-items:start"><div><small style="font-weight:900;letter-spacing:.1em;color:#8b4a36">SECURE PAYMENT</small><h2 style="margin:5px 0">Authorize ${money(ride.fare_cents/100)}</h2><p style="margin:0 0 18px;color:#666">Your fare is authorized now and captured when the trip completes.</p></div><button id="closePay" style="border:0;background:#eee;border-radius:50%;width:38px;height:38px">×</button></div><div id="paymentElement"></div><button id="payRide" style="width:100%;margin-top:18px;padding:15px;border:0;border-radius:14px;background:linear-gradient(135deg,#F6AD62,#F04449);color:#fff;font-weight:900">Authorize ride · ${money(ride.fare_cents/100)}</button><small id="payError" style="display:block;color:#a22;margin-top:10px"></small></div>`;
    state.paymentElement=elements.create('payment');state.paymentElement.mount('#paymentElement');
    return new Promise(resolve=>{
      $('#closePay').onclick=()=>{modal.remove();resolve(false)};
      $('#payRide').onclick=async()=>{const btn=$('#payRide');btn.disabled=true;btn.textContent='Authorizing…';const result=await state.stripe.confirmPayment({elements,redirect:'if_required'});if(result.error){$('#payError').textContent=result.error.message||'Payment could not be authorized.';btn.disabled=false;btn.textContent=`Authorize ride · ${money(ride.fare_cents/100)}`;return}if(['requires_capture','succeeded','processing'].includes(result.paymentIntent?.status)){modal.remove();resolve(true);return}$('#payError').textContent=`Payment status: ${result.paymentIntent?.status||'unknown'}`;btn.disabled=false}
    })
  }

  async function requestRide(){
    if(!state.selectedRide)return;if(!(await ensureAuth()))return;
    $('#confirmRide').disabled=true;$('#confirmRide').textContent='Preparing secure ride…';
    try{
      const pickup=state.pickupMarker?.getLatLng(),drop=state.destinationMarker?.getLatLng();
      const data=await api('/api/rides',{method:'POST',body:JSON.stringify({tenant_slug:new URLSearchParams(location.search).get('tenant')||'whip-equipped',rider_id:RIDER_ID(),rider_name:session?.user?.user_metadata?.full_name||'Rider',pickup_label:$('#pickupInput')?.value||'Current location',pickup_lat:pickup?.lat,pickup_lng:pickup?.lng,dropoff_label:state.destination,dropoff_lat:drop?.lat,dropoff_lng:drop?.lng,miles:state.miles,minutes:state.minutes,ride_tier:state.selectedRide.displayName,fare_cents:cents(state.selectedRide.price)})});
      state.activeRide=data.ride;
      const paid=await collectRidePayment(state.activeRide);
      if(!paid){try{await api(`/api/rides/${state.activeRide.id}/status`,{method:'PATCH',body:JSON.stringify({status:'CANCELED'})})}catch{}state.activeRide=null;setState('options');return}
      $('#matchRideType').textContent=state.selectedRide.displayName;$('#matchPrice').textContent=money(state.selectedRide.price);setState('matching');startRidePolling();
    }catch(e){console.error(e);alert(e.message||'Unable to request ride.');setState('options')}
    finally{$('#confirmRide').disabled=false;$('#confirmRide').textContent=state.selectedRide?`Request ${state.selectedRide.displayName} · ${money(state.selectedRide.price)}`:'Choose a ride'}
  }
  function startRidePolling(){clearInterval(state.pollTimer);renderBackendRide(state.activeRide);state.pollTimer=setInterval(async()=>{if(!state.activeRide)return;try{const data=await api(`/api/rides/${state.activeRide.id}`);state.activeRide=data.ride;renderBackendRide(data.ride)}catch(e){console.warn(e)}},1600)}
  function renderBackendRide(r){if(!r)return;const status=r.status;if(status==='REQUESTED'){setState('matching');$('#matchRideType').textContent=r.ride_tier;$('#matchPrice').textContent=money(r.fare_cents/100);return}if(['ACCEPTED','DRIVER_EN_ROUTE','DRIVER_ARRIVED','VERIFIED','IN_PROGRESS'].includes(status)){setState('pickup');const eta=$('.eta-big');if(eta)eta.textContent=status==='DRIVER_ARRIVED'?'Driver arrived':status==='IN_PROGRESS'?'Trip in progress':status==='VERIFIED'?'Rider verified':status==='ACCEPTED'?'Driver confirmed':'3 min';const copy=$('.driver-copy');if(copy){$('strong',copy).textContent=r.driver_name||'Driver confirmed';$('small',copy).textContent=`${r.driver_rating||'5.00'} ★ · Verified WE Driver`;$('span',copy).textContent=[r.driver_vehicle,r.driver_plate].filter(Boolean).join(' · ')}const pin=$('.pickup-code strong');if(pin&&r.pickup_pin)pin.textContent=String(r.pickup_pin).split('').join('   ');const sim=$('#simulateComplete');if(sim){sim.style.display=status==='IN_PROGRESS'?'none':'';sim.textContent=status==='DRIVER_ARRIVED'?'Your driver has arrived':status==='VERIFIED'?'Verified — waiting to start':'Shared ride is live';sim.disabled=true}return}if(status==='COMPLETED'){clearInterval(state.pollTimer);$('#receiptTotal').textContent=money(r.fare_cents/100);const fee=$('#receiptPlatformFee');if(fee?.parentElement)fee.parentElement.style.display='none';setState('complete');return}if(status==='CANCELED'){clearInterval(state.pollTimer);state.activeRide=null;setState('home')}}
  async function recoverRide(){if(!session?.access_token)return;try{const data=await api(`/api/riders/${encodeURIComponent(RIDER_ID())}/active`);if(data.ride){state.activeRide=data.ride;startRidePolling()}}catch{}}
  function normalizePaymentCopy(){const row=$('.payment-row button');if(row){const strong=$('strong',row);if(strong)strong.textContent='Secure card / wallet'}const fee=$('#receiptPlatformFee');if(fee?.parentElement)fee.parentElement.style.display='none'}
  function bindEvents(){$('#destinationButton').addEventListener('click',()=>{setState('search');setTimeout(()=>$('#dropoffInput').focus(),150)});$$('.quick-card').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.destination,presets={Home:[3.2,11],Work:[6.1,17],Airport:[13.6,27]};chooseDestination(p,...presets[p])}));$$('.back-btn').forEach(b=>b.addEventListener('click',()=>setState(b.dataset.back)));$$('#suggestions button').forEach(b=>b.addEventListener('click',()=>chooseDestination(b.dataset.place,b.dataset.miles,b.dataset.minutes)));$('#dropoffInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.value.trim())chooseDestination(e.target.value.trim(),5.5,16)});$('#confirmRide').addEventListener('click',requestRide);$('#cancelMatch').addEventListener('click',async()=>{if(state.activeRide){try{await api(`/api/rides/${state.activeRide.id}/status`,{method:'PATCH',body:JSON.stringify({status:'CANCELED'})})}catch{}state.activeRide=null;clearInterval(state.pollTimer)}setState('options')});$('#simulateComplete').addEventListener('click',()=>{});$('#newRide').addEventListener('click',()=>{state.destination=null;state.selectedRide=null;state.activeRide=null;clearInterval(state.pollTimer);setState('home')});$$('.stars button').forEach((star,i,stars)=>star.addEventListener('click',()=>stars.forEach((s,n)=>s.classList.toggle('active',n<=i))));$('#brandButton').addEventListener('click',openOperator);$('#operatorNav').addEventListener('click',()=>location.href=`operator.html?api=${encodeURIComponent(API_BASE)}`);$('#closeOperator').addEventListener('click',closeOperator);$('#applyBrand').addEventListener('click',applyBrand);$('#upgradeButton').addEventListener('click',()=>location.href=`operator.html?api=${encodeURIComponent(API_BASE)}`);$('#locateButton').addEventListener('click',()=>{if(!navigator.geolocation||!state.map)return;navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];state.pickupMarker.setLatLng(ll);state.map.setView(ll,15,{animate:true})},()=>{},{enableHighAccuracy:true,timeout:6000})})}
  function revealApp(){const splash=$('#splashScreen');if(splash)setTimeout(()=>splash.classList.add('hide'),950)}
  document.addEventListener('DOMContentLoaded',async()=>{initMap();bindEvents();hydrateBrand();renderRideOptions();normalizePaymentCopy();revealApp();await recoverRide();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
})();