(() => {
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const q=new URLSearchParams(location.search);
  const apiBase=(q.get('api')||localStorage.getItem('we-api-base')||'').replace(/\/$/,'');
  let mode='login',session=JSON.parse(localStorage.getItem('we-operator-session')||'null'),tenantId=q.get('tenant')||localStorage.getItem('we-operator-tenant')||'',dashboard=null;
  function notice(text,type=''){const n=$('#notice');n.hidden=!text;n.textContent=text||'';n.className='notice '+type}
  async function request(path,init={}){if(!apiBase)throw new Error('Add ?api=https://YOUR-WORKER.workers.dev to the Operator URL first.');const headers={'content-type':'application/json',...(init.headers||{})};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;const r=await fetch(apiBase+path,{...init,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.msg||d.message||'Request failed');return d}
  function saveSession(data){if(data?.access_token){session={access_token:data.access_token,refresh_token:data.refresh_token,user:data.user};localStorage.setItem('we-operator-session',JSON.stringify(session))}}
  function clearSession(){session=null;tenantId='';localStorage.removeItem('we-operator-session');localStorage.removeItem('we-operator-tenant')}
  function money(cents){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(cents||0)/100)}
  function row(primary,secondary,right=''){return `<div class="list-row"><div><strong>${primary}</strong><small>${secondary||''}</small></div><strong>${right}</strong></div>`}
  function renderVehicles(items=[]){$('#vehicleList').innerHTML=items.length?items.map(v=>`<div class="vehicle-row"><div><strong>${v.name}</strong><small>${v.category} · ${v.location_label} · ${v.seats} seats</small></div><div><strong>${money(v.daily_rate_cents)}/day</strong><small>${v.available?'Available':'Paused'}</small></div></div>`).join(''):'<div class="empty">No vehicles yet. Add the first car in your fleet.</div>';$('#metricFleet').textContent=`${items.length} car${items.length===1?'':'s'}`}
  function renderActivity(data){$('#ridesList').innerHTML=data.rides?.length?data.rides.map(x=>row(x.status,new Date(x.requested_at).toLocaleString(),money(x.fare_cents))).join(''):'<div class="empty">No rides yet.</div>';$('#rentalsList').innerHTML=data.rentals?.length?data.rentals.map(x=>row(x.status,new Date(x.created_at).toLocaleString(),money(x.total_cents))).join(''):'<div class="empty">No rentals yet.</div>';$('#paymentsList').innerHTML=data.payments?.length?data.payments.map(x=>row(x.status,x.resource_type,money(x.amount_cents))).join(''):'<div class="empty">No payments yet.</div>'}
  async function loadDashboard(){if(!tenantId)return;const data=await request(`/api/operators/${encodeURIComponent(tenantId)}/dashboard`);dashboard=data;const t=data.tenant;$('#metricCompany').textContent=t.name;$('#metricPlan').textContent=t.white_label_enabled?'White Label · 0%':'WE Network · 3%';$('#metricStripe').textContent=t.stripe_charges_enabled&&t.stripe_payouts_enabled?'Ready':'Needs setup';$('#brandNameInput').value=t.name||'';$('#brandPrimary').value=t.primary_color||'#F04449';$('#brandSecondary').value=t.secondary_color||'#F6AD62';$('#taglineInput').value=t.tagline||'';$('#stripeDetail').textContent=t.stripe_account_id?`Connected account ${t.stripe_account_id} · charges ${t.stripe_charges_enabled?'on':'off'} · payouts ${t.stripe_payouts_enabled?'on':'off'}`:'No Stripe connected account yet.';renderVehicles(data.vehicles||[]);renderActivity(data);$('#authCard').hidden=true;$('#companyCard').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false}
  async function discoverTenant(){const data=await request('/api/operators/mine');if(data.tenants?.length){tenantId=data.tenants[0].id;localStorage.setItem('we-operator-tenant',tenantId);await loadDashboard()}else{$('#authCard').hidden=true;$('#companyCard').hidden=false;$('#dashboard').hidden=true;$('#logout').hidden=false}}
  async function boot(){if(!apiBase){notice('This portal needs the deployed WE Core URL in ?api=… before it can operate.','error');return}if(session?.access_token){try{await request('/api/auth/me');await discoverTenant();return}catch{clearSession()}}$('#authCard').hidden=false}
  $$('.tabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.authTab;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=mode==='login'?'Sign in':'Create account';$('#password').autocomplete=mode==='login'?'current-password':'new-password'});
  $('#authForm').onsubmit=async e=>{e.preventDefault();notice('');try{const body={email:$('#email').value,password:$('#password').value,data:{product:'whip-equipped-operator'}};const data=await request(mode==='login'?'/api/auth/login':'/api/auth/signup',{method:'POST',body:JSON.stringify(body)});saveSession(data);if(!session?.access_token){notice('Account created. Check your email if confirmation is enabled, then sign in.','good');mode='login';$('#authSubmit').textContent='Sign in';return}notice('Signed in.','good');await discoverTenant()}catch(err){notice(err.message,'error')}};
  $('#companyForm').onsubmit=async e=>{e.preventDefault();try{const data=await request('/api/operators',{method:'POST',body:JSON.stringify({name:$('#companyName').value,email:$('#companyEmail').value||session?.user?.email,primary_color:$('#primaryColor').value,secondary_color:$('#secondaryColor').value})});tenantId=data.tenant.id;localStorage.setItem('we-operator-tenant',tenantId);notice('Company created. Now connect Stripe.','good');await loadDashboard()}catch(err){notice(err.message,'error')}};
  $('#connectStripe').onclick=async()=>{try{notice('Creating your Stripe Connect account…');await request(`/api/operators/${tenantId}/stripe/account`,{method:'POST',body:JSON.stringify({email:session?.user?.email})});const data=await request(`/api/operators/${tenantId}/stripe/onboarding-link`,{method:'POST',body:JSON.stringify({return_url:location.href,refresh_url:location.href})});location.assign(data.url)}catch(err){notice(err.message,'error')}};
  $('#refreshStripe').onclick=async()=>{try{const data=await request(`/api/operators/${tenantId}/stripe/status`);notice(data.ready?'Stripe is ready for charges and payouts.':'Stripe still needs onboarding information.',data.ready?'good':'');await loadDashboard()}catch(err){notice(err.message,'error')}};
  $('#whiteLabel').onclick=async()=>{try{const data=await request(`/api/operators/${tenantId}/white-label/checkout`,{method:'POST',body:JSON.stringify({success_url:location.href,cancel_url:location.href})});location.assign(data.checkout_url)}catch(err){notice(err.message,'error')}};
  $('#brandForm').onsubmit=async e=>{e.preventDefault();try{await request(`/api/operators/${tenantId}/brand`,{method:'PATCH',body:JSON.stringify({name:$('#brandNameInput').value,primary_color:$('#brandPrimary').value,secondary_color:$('#brandSecondary').value,tagline:$('#taglineInput').value})});notice('Branding saved.','good');await loadDashboard()}catch(err){notice(err.message,'error')}};
  $('#toggleVehicle').onclick=()=>{$('#vehicleForm').hidden=!$('#vehicleForm').hidden};
  $('#vehicleForm').onsubmit=async e=>{e.preventDefault();try{await request(`/api/operators/${tenantId}/vehicles`,{method:'POST',body:JSON.stringify({name:$('#vehicleName').value,daily_rate_cents:Math.round(Number($('#vehicleRate').value)*100),category:$('#vehicleCategory').value,seats:Number($('#vehicleSeats').value),location_label:$('#vehicleLocation').value||'Operator location'})});e.target.reset();$('#vehicleSeats').value='5';$('#vehicleForm').hidden=true;notice('Vehicle added to your rental inventory.','good');await loadDashboard()}catch(err){notice(err.message,'error')}};
  $('#logout').onclick=async()=>{try{await request('/api/auth/logout',{method:'POST'})}catch{}clearSession();location.reload()};
  boot();
})();