/* Generated by scripts/music-track-lengths.mjs from data/albums.json and
   assets/audio. Do not edit by hand: re-run the script after adding a song. */
export const TRACKS = {
  "who-did-the-shoot": {
    "title": "Who Did The Shoot",
    "album": "here",
    "seconds": 129.8
  },
  "runway-walk": {
    "title": "Runway Walk",
    "album": "here",
    "seconds": 115.4
  },
  "write-a-song": {
    "title": "Write a Song",
    "album": "here",
    "seconds": 137.4
  },
  "here": {
    "title": "Here",
    "album": "here",
    "seconds": 96.1
  },
  "antisocial": {
    "title": "Antisocial",
    "album": "here",
    "seconds": 176.9
  },
  "lightroom": {
    "title": "Lightroom",
    "album": "here",
    "seconds": 132.3
  },
  "got-wifi": {
    "title": "Got WiFi?",
    "album": "prim3",
    "seconds": 92.4
  },
  "environmental-injustice": {
    "title": "Environmental Injustice",
    "album": "equity-uprise",
    "seconds": 162.9
  },
  "environmental-injustice-brave": {
    "title": "Environmental Injustice (Brave mix)",
    "album": "equity-uprise",
    "seconds": 254.8
  },
  "please-set-me-free": {
    "title": "Please Set Me Free",
    "album": "equity-uprise",
    "seconds": 202.5
  },
  "money-or-the-power": {
    "title": "Money or the Power",
    "album": "equity-uprise",
    "seconds": 216.1
  },
  "deep-end": {
    "title": "Deep End",
    "album": "heal-the-3",
    "seconds": 165.6
  },
  "heal-the-3rd-world": {
    "title": "Heal the 3rd World",
    "album": "heal-the-3",
    "seconds": 146
  },
  "vaunt": {
    "title": "Vaunt (Acoustic)",
    "album": "vaunt-ep",
    "seconds": 92.4
  },
  "dealer-plates": {
    "title": "Dealer Plates (A-Side)",
    "album": "whip-equipped",
    "seconds": 97.4
  },
  "dealer-plates-b": {
    "title": "Dealer Plates (B-Side)",
    "album": "whip-equipped",
    "seconds": 22.8
  },
  "upset": {
    "title": "Upset",
    "album": "singles",
    "seconds": 184.2
  },
  "you-the-feds": {
    "title": "You the Feds",
    "album": "cia-mind-control",
    "seconds": 232.9
  },
  "pull-up": {
    "title": "Pull Up",
    "album": "cia-mind-control",
    "seconds": 150.4
  },
  "niggy-nigg": {
    "title": "Niggy Nigg Niggr",
    "album": "cia-mind-control",
    "gated": true
  }
};
