import Stripe from 'npm:stripe@14';
const stripe=new Stripe(Deno.env.get('STRIPE_SK')!);const SB=Deno.env.get('SUPABASE_URL')!;const SRV=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const SITE='https://mcclusterishere.github.io/Lvl-3-Media';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
async function rest(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',SRV);h.set('Authorization',`Bearer ${SRV}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${SB}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return j({error:'POST only'},405);
 const auth=req.headers.get('Authorization')||'';const who=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:SRV,Authorization:auth}}).then(r=>r.ok?r.json():null);if(!who?.id)return j({error:'sign_in_first'},401);
 const org=(await rest('orgs?slug=eq.level-3-media&select=id&limit=1'))?.[0];if(!org)return j({error:'org_missing'},500);const mem=(await rest(`org_members?org_id=eq.${org.id}&profile_id=eq.${who.id}&role=eq.owner&select=org_id&limit=1`))?.[0];if(!mem)return j({error:'owner_required'},403);
 const body=await req.json().catch(()=>({}));const plan=String(body.plan||'');const cfg=plan==='standard_33'?{amount:3300,label:'Level 3 Media Platform — $33/month',share:'0'}:plan==='share_1650_50'?{amount:1650,label:'Level 3 Media Platform — $16.50/month + 50% revenue share',share:'5000'}:null;if(!cfg)return j({error:'invalid_plan'},400);
 const settings=(await rest(`l3_store_settings?org_id=eq.${org.id}&select=*&limit=1`))?.[0];if(settings?.billing_status==='active'&&settings?.plan_code===plan)return j({status:'already_active'});
 let customer=settings?.platform_stripe_customer_id as string|undefined;if(!customer){const c=await stripe.customers.create({email:who.email||undefined,name:'Level 3 Media',metadata:{mccluster_org_id:org.id,app_key:'level-3-media-web'}});customer=c.id;await rest(`l3_store_settings?org_id=eq.${org.id}`,{method:'PATCH',body:JSON.stringify({platform_stripe_customer_id:customer,updated_at:new Date().toISOString()})});}
 const metadata={kind:'l3_platform_subscription',mccluster_org_id:org.id,app_key:'level-3-media-web',plan_code:plan,revenue_share_bps:cfg.share};
 const session=await stripe.checkout.sessions.create({mode:'subscription',customer,line_items:[{price_data:{currency:'usd',product_data:{name:cfg.label,description:plan==='share_1650_50'?'Platform access plus a 50% application fee on Level 3 digital-product gross sales processed through the platform.':'Platform access with no Level 3 product revenue share.'},unit_amount:cfg.amount,recurring:{interval:'month'}},quantity:1}],subscription_data:{metadata},metadata,success_url:`${SITE}/dashboard.html?billing=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${SITE}/dashboard.html?billing=canceled`,allow_promotion_codes:false});
 return j({url:session.url,plan});
});