import Stripe from 'npm:stripe@14';
const stripe=new Stripe(Deno.env.get('STRIPE_SK')!);const SB=Deno.env.get('SUPABASE_URL')!;const SRV=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
async function rest(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',SRV);h.set('Authorization',`Bearer ${SRV}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${SB}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return j({error:'POST only'},405);const b=await req.json().catch(()=>({}));const sid=String(b.session_id||'');if(!sid.startsWith('cs_'))return j({error:'bad_session'},400);
 const order=(await rest(`l3_orders?stripe_checkout_session_id=eq.${encodeURIComponent(sid)}&select=*&limit=1`))?.[0];if(!order?.connected_account_id)return j({error:'order_not_found'},404);let session:any;try{session=await stripe.checkout.sessions.retrieve(sid,{expand:['payment_intent']},{stripeAccount:order.connected_account_id});}catch{return j({error:'session_not_found'},404)}if(session.payment_status!=='paid')return j({error:'payment_not_complete'},402);
 const product=(await rest(`l3_products?id=eq.${order.product_id}&select=id,title,asset_path,file_name,version&limit=1`))?.[0];if(!product?.asset_path)return j({error:'asset_missing'},409);
 const email=session.customer_details?.email||session.customer_email||order.customer_email||null;const pi=typeof session.payment_intent==='object'?session.payment_intent?.id:session.payment_intent;
 await rest(`l3_orders?id=eq.${order.id}`,{method:'PATCH',body:JSON.stringify({status:'paid',customer_email:email,customer_name:session.customer_details?.name||null,stripe_payment_intent_id:pi||null,paid_at:order.paid_at||new Date().toISOString(),updated_at:new Date().toISOString()})});
 let ent=(await rest(`l3_entitlements?order_id=eq.${order.id}&select=*&limit=1`))?.[0];if(!ent){const inserted=await rest('l3_entitlements',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({order_id:order.id,product_id:order.product_id,customer_email:email})});ent=inserted?.[0];}if(!ent||ent.revoked_at)return j({error:'download_revoked'},403);
 const sr=await fetch(`${SB}/storage/v1/object/sign/l3-product-files/${product.asset_path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{apikey:SRV,Authorization:`Bearer ${SRV}`,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:300})});const signed=await sr.json().catch(()=>({}));if(!sr.ok||!signed.signedURL)return j({error:'sign_failed'},500);const url=String(signed.signedURL).startsWith('http')?signed.signedURL:`${SB}/storage/v1${signed.signedURL}`;
 const ip=(req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim();await rest(`l3_entitlements?id=eq.${ent.id}`,{method:'PATCH',body:JSON.stringify({download_count:Number(ent.download_count||0)+1,last_download_at:new Date().toISOString()})});await rest('l3_download_events',{method:'POST',body:JSON.stringify({entitlement_id:ent.id,ip_hash:await sha(ip),user_agent:(req.headers.get('user-agent')||'').slice(0,500)})});
 return j({url,expires_in:300,file_name:product.file_name||`${product.title}.zip`,title:product.title,version:product.version});
});