import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const migration = await readFile(
  new URL('../../supabase/migrations/20260919055029_universal_ingestion_entity_resolution_v1.sql', import.meta.url),
  'utf8'
);
const ingestion = await readFile(new URL('../src/tools/ingestion.mjs', import.meta.url), 'utf8');

test('Gate 2 has universal connectors runs records facts aliases and resolution history', () => {
  for (const table of [
    'ops_ingest_connectors',
    'ops_ingest_runs',
    'ops_ingest_records',
    'ops_fact_claims',
    'ops_entity_aliases',
    'ops_entity_resolution_events'
  ]) {
    assert.match(migration, new RegExp(`create table if not exists public\\.${table}`));
  }
});

test('connector contract covers every required ingestion class', () => {
  for (const kind of ['api','database','file','email','calendar','web','telemetry','event_stream','mcp','internal']) {
    assert.ok(migration.includes(`'${kind}'`), `missing connector kind ${kind}`);
  }
  for (const field of ['content_hash','trace_id','retention_policy','license_policy','idempotency_key','cursor_before','cursor_after']) {
    assert.ok(migration.includes(field), `missing ingest contract field ${field}`);
  }
});

test('ingestion is force-RLS and service mediated', () => {
  assert.match(migration, /force row level security/);
  assert.match(migration, /revoke all on table public\.%I from public, anon, authenticated/);
  assert.match(migration, /grant execute on function public\.ops_ingest_records_service/);
  assert.match(migration, /grant execute on function public\.ops_entity_resolve_service/);
  assert.doesNotMatch(migration, /grant execute on function public\.ops_entity_resolve_service[^;]+to authenticated/i);
});

test('source adapters ingest existing canonical systems without replacing them', () => {
  for (const trigger of [
    'ops_ingest_fabric_event_t',
    'ops_ingest_kb_document_t',
    'ops_ingest_inbox_message_t',
    'ops_ingest_repo_event_t'
  ]) assert.ok(migration.includes(trigger), `missing source adapter ${trigger}`);
  assert.match(migration, /'fabric\.events'/);
  assert.match(migration, /'knowledge\.documents'/);
  assert.match(migration, /'communications\.inbox'/);
  assert.match(migration, /'repositories\.events'/);
});

test('records are deterministic and replayable', () => {
  assert.match(migration, /extensions\.digest/);
  assert.match(migration, /unique \(org_id, connector_id, idempotency_key\)/);
  assert.match(migration, /mode in \('initial','incremental','replay','manual'\)/);
  assert.match(migration, /status in \('running','succeeded','partial','failed'\)/);
  assert.match(migration, /last_error/);
});

test('entity resolution preserves provenance and facts preserve conflicts', () => {
  assert.match(migration, /ops_entity_resolution_events/);
  assert.match(migration, /source_record_id/);
  assert.match(migration, /status='rejected'/);
  assert.match(migration, /Superseded by explicit owner resolution/);
  assert.match(migration, /set status='conflicting'/);
  assert.match(migration, /value_hash<>v_hash/);
});

test('entity resolution requires an authenticated owner', () => {
  assert.match(migration, /actor_user is required/);
  assert.match(migration, /owner permission required/);
  assert.match(ingestion, /options\?\.actor\?\.user_id/);
  assert.match(ingestion, /ops_entity_resolve_service/);
});

test('Core exposes governed Gate 2 primitives rather than raw SQL', () => {
  for (const tool of [
    'core.ingest.connectors',
    'core.ingest.records',
    'core.ingest.run.begin',
    'core.ingest.record.write',
    'core.ingest.run.finish',
    'core.entity.aliases',
    'core.entity.resolve',
    'core.facts.query',
    'core.facts.claim'
  ]) assert.ok(ingestion.includes(tool), `missing tool ${tool}`);
  assert.doesNotMatch(ingestion, /select \* from|insert into|update public\./i);
});


test('Gate 2 closes the historical repository-event replay gap before attaching its source adapter', () => {
  assert.match(migration, /create table if not exists public\.ops_repo_events/);
  assert.match(migration, /id bigint generated by default as identity primary key/);
  assert.match(migration, /paths jsonb not null default '\[\]'::jsonb/);
  assert.match(migration, /test_summary jsonb not null default '\{\}'::jsonb/);
  assert.match(migration, /create index if not exists ops_repo_events_repo_observed_idx/);
  assert.match(migration, /grant all on table public\.ops_repo_events to service_role/);
});
