plugins {
    id 'com.android.application'
}

android {
    namespace = 'org.mccluster.smsrelay'
    compileSdk = 36

    defaultConfig {
        applicationId = 'org.mccluster.smsrelay'
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = '1.0.0-beta1'
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
