// Stable approval/control API for the Equity Uprise Desk.
// Request/decision semantics remain owned by the existing McCluster control plane;
// this endpoint simply gives the frontend one Policy OS surface.
import { SB, SRV, authorize, cors, db, json, orgBySlug, safeText, verifyCaller } from "../_shared/eu-policy-os.ts";
const ANON=Deno.env.get("SUPABASE_ANON_KEY")??"";
async function userRpc(req:Request,fn:string,args:any){const auth=req.headers.get("authorization")??"";if(!auth||!ANON)throw new Error("user RPC unavailable");const r=await fetch(`${SB}/rest/v1/rpc/${fn}`,{method:"POST",headers:{apikey:ANON,authorization:auth,"content-type":"application/json"},body:JSON.stringify(args)});const text=await r.text();if(!r.ok)throw new Error(`control ${r.status}: ${text.slice(0,1000)}`);return text?JSON.parse(text):null;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const caller=await verifyCaller(req);if(!caller)return json({error:"authentication required"},401);try{const org=await orgBySlug("mccluster");const body=await req.json();const action=safeText(body.action,40);
 if(action==="capabilities"){const caps=await userRpc(req,"control_my_capabilities",{p_org:org.id});return json({ok:true,capabilities:caps});}
 if(action==="request-approval"){const capability=safeText(body.capability,120),resourceType=safeText(body.resource_type,120),resourceId=safeText(body.resource_id,200),requestHash=safeText(body.request_hash,256),reason=safeText(body.reason,1000);if(!capability||!resourceType||!resourceId||requestHash.length<16)return json({error:"capability, resource_type, resource_id and request_hash required"},400);const id=await userRpc(req,"control_request_approval",{p_org:org.id,p_capability:capability,p_resource_type:resourceType,p_resource_id:resourceId,p_request_hash:requestHash,p_reason:reason||null,p_ttl_seconds:Math.max(60,Math.min(Number(body.ttl_seconds)||1800,3600))});return json({ok:true,approval_id:Array.isArray(id)?id[0]:id});}
 if(action==="decide"){const id=safeText(body.approval_id,80),state=safeText(body.state,20);if(!id||!["approved","denied"].includes(state))return json({error:"approval_id and approved/denied state required"},400);const row=await userRpc(req,"control_decide_approval",{p_approval_id:id,p_state:state});return json({ok:true,approval:row});}
 if(action==="pending"){const d=await authorize(caller,org.id,"control.read");if(!d.allowed)return json({error:"control.read permission required"},403);const rows=await db(`control_approvals?org_id=eq.${org.id}&state=eq.pending&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=*&order=created_at.desc&limit=200`);return json({ok:true,approvals:rows??[]});}
 if(action==="commands"){const d=await authorize(caller,org.id,"control.read");if(!d.allowed)return json({error:"control.read permission required"},403);const rows=await db(`control_commands?org_id=eq.${org.id}&select=*&order=created_at.desc&limit=200`);return json({ok:true,commands:rows??[]});}
 return json({error:"unknown action"},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500);}});