import Stripe from 'npm:stripe@14';
const stripe=new Stripe(Deno.env.get('STRIPE_SK')!);const SB=Deno.env.get('SUPABASE_URL')!;const SRV=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const SITE='https://mcclusterishere.github.io/Lvl-3-Media';
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
async function rest(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',SRV);h.set('Authorization',`Bearer ${SRV}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${SB}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return j({error:'POST only'},405);const b=await req.json().catch(()=>({}));const productId=String(b.product_id||'');if(!/^[0-9a-f-]{36}$/i.test(productId))return j({error:'bad_product'},400);
 const org=(await rest('orgs?slug=eq.level-3-media&select=id&limit=1'))?.[0];const s=(await rest(`l3_store_settings?org_id=eq.${org.id}&select=*&limit=1`))?.[0];if(!s||!['active','trialing'].includes(s.billing_status)||!s.storefront_enabled)return j({error:'store_unavailable'},402);
 const p=(await rest(`l3_products?id=eq.${productId}&org_id=eq.${org.id}&status=eq.published&select=*&limit=1`))?.[0];if(!p)return j({error:'product_unavailable'},404);
 const seller=(await rest(`org_stripe_accounts?org_id=eq.${org.id}&stripe_account_id=eq.${encodeURIComponent(s.connected_account_id||'')}&charges_enabled=eq.true&select=stripe_account_id,onboarding_status&limit=1`))?.[0];if(!seller?.stripe_account_id||seller.onboarding_status!=='ready')return j({error:'seller_not_ready'},409);
 const fee=s.plan_code==='share_1650_50'?Math.round(Number(p.price_cents)*0.5):0;const orderId=crypto.randomUUID();const metadata={kind:'l3_product_sale',l3_order_id:orderId,l3_product_id:p.id,mccluster_org_id:org.id,plan_code:s.plan_code,application_fee_cents:String(fee)};
 const params:any={mode:'payment',payment_method_types:['card'],line_items:[{price_data:{currency:p.currency||'usd',product_data:{name:p.title,description:(p.short_description||p.description||'').slice(0,250)},unit_amount:p.price_cents},quantity:1}],metadata,payment_intent_data:{metadata,...(fee>0?{application_fee_amount:fee}:{})},customer_creation:'always',billing_address_collection:'auto',success_url:`${SITE}/download.html?session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${SITE}/shop.html?canceled=1`};
 let session:any;try{session=await stripe.checkout.sessions.create(params,{stripeAccount:seller.stripe_account_id});}catch(e){console.error(e);return j({error:'checkout_failed'},502)}
 await rest('l3_orders',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:orderId,org_id:org.id,product_id:p.id,stripe_checkout_session_id:session.id,connected_account_id:seller.stripe_account_id,amount_cents:p.price_cents,application_fee_cents:fee,currency:p.currency||'usd',status:'pending',plan_code:s.plan_code,metadata})});
 return j({url:session.url});
});