// Recurring policy/research intelligence monitor runner.
// Monitors observe; they do not publish or file anything. Interesting results
// become monitor hits + canonical events for humans/workflows to act on.
import { db, emitEvent, json, rpc, safeText, sha256Hex } from "../_shared/eu-policy-os.ts";
const SECRET=Deno.env.get("EU_WORKER_SECRET")??"";

async function hit(m:any,input:{external_id?:string;url?:string;title?:string;summary?:string;occurred_at?:string;relevance?:number;classification?:any;raw?:any}){
 const external=input.external_id||await sha256Hex(`${input.url||""}|${input.title||""}|${input.summary||""}`);
 let row:any;try{row=(await db("eu_monitor_hits",{method:"POST",body:JSON.stringify({org_id:m.org_id,monitor_id:m.id,initiative_id:m.initiative_id,external_id:external,url:input.url||"",title:input.title||"",summary:input.summary||"",occurred_at:input.occurred_at||null,relevance:input.relevance??null,classification:input.classification||{},raw:input.raw||{},state:"new"})}))?.[0];}catch(e){if(!String(e).includes("duplicate key"))throw e;await db(`eu_monitor_hits?monitor_id=eq.${m.id}&external_id=eq.${encodeURIComponent(external)}`,{method:"PATCH",body:JSON.stringify({last_seen_at:new Date().toISOString(),raw:input.raw||{}})});return null;}
 if(row)await emitEvent({orgId:m.org_id,initiativeId:m.initiative_id,eventType:"monitor.hit",entityType:"eu_monitor_hits",entityId:row.id,sourceSystem:m.provider||m.monitor_type,sourceId:external,data:{monitor_id:m.id,monitor_type:m.monitor_type,title:row.title,url:row.url,summary:row.summary},idempotencyKey:`monitor-hit:${m.id}:${external}`});return row;
}
function strip(s:string){return s.replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\s+/g," ").trim();}
function tags(xml:string,name:string){const re=new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"gi");return [...xml.matchAll(re)].map(x=>x[1]);}
function first(block:string,names:string[]){for(const n of names){const m=block.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,"i"));if(m)return strip(m[1].replace(/<!\[CDATA\[|\]\]>/g,""));}return"";}
async function rss(m:any){const url=safeText(m.query?.url,1500);if(!url)throw new Error("rss monitor requires query.url");const r=await fetch(url,{headers:{"user-agent":"Equity-Uprise-Monitor/1.0"}});if(!r.ok)throw new Error(`rss ${r.status}`);const xml=await r.text();const entries=[...tags(xml,"item"),...tags(xml,"entry")].slice(0,100);let n=0;for(const b of entries){const title=first(b,["title"]),link=first(b,["link"])||((b.match(/<link[^>]+href=["']([^"']+)/i)||[])[1]||""),guid=first(b,["guid","id"])||link||title,summary=first(b,["description","summary","content"]),date=first(b,["pubDate","published","updated"]);if(await hit(m,{external_id:guid,url:link,title,summary:summary.slice(0,4000),occurred_at:date&&Number.isFinite(Date.parse(date))?new Date(date).toISOString():undefined,raw:{guid}}))n++;}return{hits:n,entries:entries.length};}
async function sourceHealth(m:any){let sources:any[]=[];if(m.query?.source_id)sources=await db(`eu_sources?id=eq.${encodeURIComponent(String(m.query.source_id))}&select=*`);else if(m.query?.research_project_id)sources=await db(`eu_sources?research_project_id=eq.${encodeURIComponent(String(m.query.research_project_id))}&select=*`);else if(m.query?.url)sources=[{id:null,url:String(m.query.url),title:String(m.query.title||m.name)}];else throw new Error("source-health monitor needs source_id, research_project_id or url");let broken=0;for(const s of sources.slice(0,100)){if(!s.url)continue;let status=0;try{let r=await fetch(s.url,{method:"HEAD",redirect:"follow"});if(r.status===405||r.status===403)r=await fetch(s.url,{method:"GET",headers:{Range:"bytes=0-1024"},redirect:"follow"});status=r.status;}catch{}const ok=status>=200&&status<400;if(s.id)await db(`eu_sources?id=eq.${s.id}`,{method:"PATCH",body:JSON.stringify({verification:ok?(s.verification==="verified"?"verified":"retrieved"):"broken",last_checked_at:new Date().toISOString()})});if(!ok){broken++;await hit(m,{external_id:`${s.id||s.url}:${status}`,url:s.url,title:`Source unavailable: ${s.title||s.url}`,summary:`HTTP status ${status||"network failure"}`,classification:{kind:"source-health",broken:true,http_status:status},raw:{source_id:s.id,status}});}}return{checked:sources.length,broken};}
async function openAlexLiterature(m:any){const q=safeText(m.query?.q||m.query?.search,500);if(!q)throw new Error("research-literature monitor requires query.q");const url=`https://api.openalex.org/works?search=${encodeURIComponent(q)}&per-page=${Math.min(Number(m.query?.limit)||25,100)}`;const r=await fetch(url,{headers:{"user-agent":"Equity Uprise research monitor (mailto:matthew@mccluster.org)"}});if(!r.ok)throw new Error(`OpenAlex ${r.status}`);const j=await r.json();let n=0;for(const w of j.results||[]){if(await hit(m,{external_id:w.id,url:w.doi||w.primary_location?.landing_page_url||w.id,title:w.display_name||"",summary:`${w.publication_year||""} · cited by ${w.cited_by_count??0}`,occurred_at:w.publication_date?`${w.publication_date}T00:00:00Z`:undefined,relevance:w.relevance_score?Math.min(1,Number(w.relevance_score)):undefined,classification:{kind:"research-literature",doi:w.doi,cited_by_count:w.cited_by_count},raw:w}))n++;}return{hits:n,total:j.meta?.count??null};}
async function regulationWatch(m:any){const key=Deno.env.get("REGULATIONS_GOV_API_KEY")??"";if(!key)return{not_configured:true,requires:["REGULATIONS_GOV_API_KEY"]};const base=Deno.env.get("REGULATIONS_GOV_API_BASE")||"https://api.regulations.gov/v4";const kind=["documents","dockets","comments"].includes(String(m.query?.resource))?String(m.query.resource):"documents";const qs=new URLSearchParams();const filters=m.query?.filters||{};for(const [k,v] of Object.entries(filters))if(v!==null&&v!==undefined)qs.set(`filter[${k}]`,String(v));qs.set("page[size]",String(Math.min(Number(m.query?.limit)||25,250)));const r=await fetch(`${base}/${kind}?${qs}`,{headers:{"X-Api-Key":key}});if(!r.ok)throw new Error(`Regulations.gov ${r.status}: ${(await r.text()).slice(0,500)}`);const j=await r.json();let n=0;for(const x of j.data||[]){const a=x.attributes||{};if(await hit(m,{external_id:x.id,url:`https://www.regulations.gov/${kind.slice(0,-1)}/${x.id}`,title:a.title||a.documentId||x.id,summary:(a.docAbstract||a.comment||"").slice(0,4000),occurred_at:a.postedDate||a.lastModifiedDate||undefined,classification:{kind:`regulations-${kind}`,docket_id:a.docketId,agency_id:a.agencyId},raw:x}))n++;}return{hits:n,count:(j.data||[]).length};}
async function siteChange(m:any){const url=safeText(m.query?.url,1500);if(!url)throw new Error("stakeholder-site monitor requires query.url");const r=await fetch(url,{headers:{"user-agent":"Equity-Uprise-Monitor/1.0"}});if(!r.ok)throw new Error(`site ${r.status}`);const text=(await r.text()).slice(0,2_000_000),hash=await sha256Hex(text),prior=String(m.cursor?.sha256||"");await db(`eu_monitors?id=eq.${m.id}`,{method:"PATCH",body:JSON.stringify({cursor:{...(m.cursor||{}),sha256:hash,last_status:r.status,last_checked_at:new Date().toISOString()}})});if(prior&&prior!==hash)await hit(m,{external_id:hash,url,title:`Website changed: ${m.name}`,summary:"Monitored page content changed since the previous successful check.",classification:{kind:"site-change",previous_sha256:prior,current_sha256:hash},raw:{status:r.status}});return{changed:!!prior&&prior!==hash,sha256:hash};}
async function citation(m:any){const pid=safeText(m.query?.publication_id,80);if(!pid)throw new Error("citation monitor requires publication_id");const p=(await db(`eu_publications?id=eq.${encodeURIComponent(pid)}&select=id,doi,stable_id,initiative_id&limit=1`))?.[0];if(!p)throw new Error("publication missing");const day=new Date().toISOString().slice(0,10);await db("eu_jobs",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify({org_id:m.org_id,initiative_id:m.initiative_id,job_type:"citation.refresh",provider:"openalex",action:"citation-snapshot",capability:"policy.read",resource_type:"eu_publications",resource_id:p.id,payload:{publication_id:p.id},state:"queued",idempotency_key:`citation:${p.id}:openalex:${day}`})});return{queued:true,publication_id:p.id};}
async function custom(m:any){const url=safeText(m.query?.url,1500);if(!url)throw new Error("custom-api monitor requires query.url");const headers:Record<string,string>={Accept:"application/json"};if(m.query?.auth_env){const v=Deno.env.get(String(m.query.auth_env));if(v)headers.Authorization=String(m.query?.auth_prefix||"Bearer ")+v;}const r=await fetch(url,{headers});const text=await r.text();if(!r.ok)throw new Error(`custom api ${r.status}: ${text.slice(0,500)}`);const hash=await sha256Hex(text),prior=String(m.cursor?.sha256||"");await db(`eu_monitors?id=eq.${m.id}`,{method:"PATCH",body:JSON.stringify({cursor:{...(m.cursor||{}),sha256:hash}})});if(prior&&prior!==hash)await hit(m,{external_id:hash,url,title:`API changed: ${m.name}`,summary:"Monitored API response changed.",classification:{kind:"custom-api"},raw:{preview:text.slice(0,5000)}});return{changed:!!prior&&prior!==hash};}
async function runOne(m:any){switch(m.monitor_type){case"rss":return rss(m);case"source-health":return sourceHealth(m);case"research-literature":return openAlexLiterature(m);case"government-docket":case"legislation":case"agenda":return regulationWatch(m);case"stakeholder-site":return siteChange(m);case"citation":return citation(m);case"custom-api":return custom(m);default:return{not_configured:true,reason:`monitor type ${m.monitor_type} needs a provider-specific adapter`};}}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"POST required"},405);if(!SECRET||req.headers.get("x-eu-worker-secret")!==SECRET)return json({error:"unauthorized"},401);try{const body=await req.json().catch(()=>({}));const ms=await rpc("eu_claim_monitors_service",{p_limit:Math.max(1,Math.min(Number(body.limit)||10,50))});const monitors=Array.isArray(ms)?ms:ms?[ms]:[];const results=[];for(const m of monitors){try{const result=await runOne(m);results.push({id:m.id,ok:true,result});await emitEvent({orgId:m.org_id,initiativeId:m.initiative_id,eventType:"monitor.ran",entityType:"eu_monitors",entityId:m.id,sourceSystem:"eu-monitor",data:{monitor_type:m.monitor_type,result}}).catch(()=>{});}catch(e){const error=e instanceof Error?e.message:String(e);results.push({id:m.id,ok:false,error});await emitEvent({orgId:m.org_id,initiativeId:m.initiative_id,eventType:"monitor.failed",entityType:"eu_monitors",entityId:m.id,sourceSystem:"eu-monitor",data:{error,monitor_type:m.monitor_type}}).catch(()=>{});}}return json({ok:true,claimed:monitors.length,results});}catch(e){return json({error:e instanceof Error?e.message:String(e)},500);}});