-- THE BOT'S KNOWLEDGE. GENERATED — do not edit by hand.
--
--     node scripts/kb-build.mjs > supabase/migrations/0033_knowledge_base.sql
--
-- McCluster figures come from data/offers.json through the same derive()
-- and priceOf() the website renders with. The market bands come from
-- data/market-rates.json, and every comparison between the two is
-- arithmetic rather than assertion — including the golden 33% ceiling,
-- which scripts/golden-check.mjs re-derives and enforces.
-- GENERATED BY scripts/kb-build.mjs. Do not edit by hand: edit the
-- ledger or the script and run it again.
--
-- Embeddings are left null on purpose. kb_search() fuses full-text and
-- vector ranks and works on full-text alone, so the bot answers today
-- with no embedding provider configured; running /kb_put later fills
-- the vectors in and the same rows get better, rather than different.
begin;

with house as (select id from public.orgs where slug = 'mccluster')
select 1;

-- Domain and hosting (7 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'offer', 'https://matthew.mccluster.org/sites.html#runway', 'Domain and hosting', 'The runway your business takes off from, and here is what the runway actually is. The domain is your address: yourname.com, rented a year at a time, and it is yours, not a slug hanging off somebody else''s platform. The hosting is the ground it sits on: the machine that answers when somebody types that address, kept online, kept secure, kept backed up. Two bills, both mine to run. The website itself I build for free.

## Price
$66 to go live.
Then $33/month.
First year all in: $429.

## Paying the year up front
$393 to go live, year of hosting paid.
Then $360/year.
Paying the year together saves $36.

## What is included
- Domain registration, one year
- Hosting
- SSL
- The website build itself, free
- Backups

## What is not included
- Ongoing website management
- Ongoing social media management
- Photography
- Video production
- Songwriting
- Campaign strategy

## Equity Uprise
Domain and hosting has no Equity Uprise version. There is no reason to trade a share of your revenue for an address and a machine to keep it online.

## How to buy it
- Get the address: https://matthew.mccluster.org/pay.html?offer=domain-hosting-start
- Get the address: https://matthew.mccluster.org/pay.html?offer=domain-hosting-year
Or start from the cards at https://matthew.mccluster.org/sites.html
', 'ledger', '1296:f9cd8904', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#runway';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Domain and hosting', 'The runway your business takes off from, and here is what the runway actually is. The domain is your address: yourname.com, rented a year at a time, and it is yours, not a slug hanging off somebody else''s platform. The hosting is the ground it sits on: the machine that answers when somebody types that address, kept online, kept secure, kept backed up. Two bills, both mine to run. The website itself I build for free.', 105),
  (1, 'Domain and hosting — Price', '$66 to go live.
Then $33/month.
First year all in: $429.', 14),
  (2, 'Domain and hosting — Paying the year up front', '$393 to go live, year of hosting paid.
Then $360/year.
Paying the year together saves $36.', 23),
  (3, 'Domain and hosting — What is included', '- Domain registration, one year
- Hosting
- SSL
- The website build itself, free
- Backups', 23),
  (4, 'Domain and hosting — What is not included', '- Ongoing website management
- Ongoing social media management
- Photography
- Video production
- Songwriting
- Campaign strategy', 33),
  (5, 'Domain and hosting — Equity Uprise', 'Domain and hosting has no Equity Uprise version. There is no reason to trade a share of your revenue for an address and a machine to keep it online.', 37),
  (6, 'Domain and hosting — How to buy it', '- Get the address: https://matthew.mccluster.org/pay.html?offer=domain-hosting-start
- Get the address: https://matthew.mccluster.org/pay.html?offer=domain-hosting-year
Or start from the cards at https://matthew.mccluster.org/sites.html', 59)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#runway';

-- Anti-Social (Anti-Social Management) (6 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'offer', 'https://matthew.mccluster.org/sites.html#anti-social', 'Anti-Social (Anti-Social Management)', 'Your website and your social presence, run as one service. Website management and social management are not separate products here.

## Price
$875 per month.

## Equity Uprise price
$437.50 per month.
Plus 50% of approved eligible connected online revenue, for up to 12 months, ending at the earlier of the term or a $105,000 cap. No ownership is taken.

## What is included
- Website build or transition
- Hosting, SSL and backups
- Routine website edits
- Website maintenance
- Payment-rail connections
- Domain support
- Social account management
- Content scheduling
- Caption and posting support
- Brand-voice maintenance
- Strategy and reporting
- Client approval workflow

## What is not included
- Original photography and video shoots: those belong to Who Did the Shoot unless a written content allowance says otherwise

## How to buy it
- Start the free month: https://matthew.mccluster.org/pay.html?offer=anti-social-m
Or start from the cards at https://matthew.mccluster.org/sites.html
', 'ledger', '998:b9482a15', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#anti-social';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Anti-Social (Anti-Social Management)', 'Your website and your social presence, run as one service. Website management and social management are not separate products here.', 33),
  (1, 'Anti-Social (Anti-Social Management) — Price', '$875 per month.', 4),
  (2, 'Anti-Social (Anti-Social Management) — Equity Uprise price', '$437.50 per month.
Plus 50% of approved eligible connected online revenue, for up to 12 months, ending at the earlier of the term or a $105,000 cap. No ownership is taken.', 43),
  (3, 'Anti-Social (Anti-Social Management) — What is included', '- Website build or transition
- Hosting, SSL and backups
- Routine website edits
- Website maintenance
- Payment-rail connections
- Domain support
- Social account management
- Content scheduling
- Caption and posting support
- Brand-voice maintenance
- Strategy and reporting
- Client approval workflow', 76),
  (4, 'Anti-Social (Anti-Social Management) — What is not included', '- Original photography and video shoots: those belong to Who Did the Shoot unless a written content allowance says otherwise', 31),
  (5, 'Anti-Social (Anti-Social Management) — How to buy it', '- Start the free month: https://matthew.mccluster.org/pay.html?offer=anti-social-m
Or start from the cards at https://matthew.mccluster.org/sites.html', 38)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#anti-social';

-- Who Did the Shoot (5 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'offer', 'https://matthew.mccluster.org/sites.html#who-did-the-shoot', 'Who Did the Shoot', 'The original visual-content service. Photography and video, shot and graded in house.

## Price
From $201 per project.
- Portrait · headshot session: $285 — the session
- Event coverage: $201 — per hour · two-hour minimum
- Video half-day: $990 — up to five hours · kit included
- Video full-day: $1,600 — eight hours · kit included
- Event film: $2,040 — full day + highlight film
- Photo brand half-day: $938 — up to four hours
- Photo brand full-day: $1,842.50 — eight hours
- Music video: $2,740 — from · one day, one location
- Brand film: $3,440 — shoot + edit · score included

## Equity Uprise price
Equity terms structured during discovery.

## What is included
- Photography
- Video production
- Event coverage
- Brand shoots
- Product photography
- Interviews
- Short-form and promotional video
- Editing and grading
- Delivery of final assets

## How to buy it
- Book a date: https://matthew.mccluster.org/pay.html?offer=booking-deposit
Or start from the cards at https://matthew.mccluster.org/sites.html
', 'ledger', '1017:b16e5260', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#who-did-the-shoot';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Who Did the Shoot', 'The original visual-content service. Photography and video, shot and graded in house.', 22),
  (1, 'Who Did the Shoot — Price', 'From $201 per project.
- Portrait · headshot session: $285 — the session
- Event coverage: $201 — per hour · two-hour minimum
- Video half-day: $990 — up to five hours · kit included
- Video full-day: $1,600 — eight hours · kit included
- Event film: $2,040 — full day + highlight film
- Photo brand half-day: $938 — up to four hours
- Photo brand full-day: $1,842.50 — eight hours
- Music video: $2,740 — from · one day, one location
- Brand film: $3,440 — shoot + edit · score included', 122),
  (2, 'Who Did the Shoot — Equity Uprise price', 'Equity terms structured during discovery.', 11),
  (3, 'Who Did the Shoot — What is included', '- Photography
- Video production
- Event coverage
- Brand shoots
- Product photography
- Interviews
- Short-form and promotional video
- Editing and grading
- Delivery of final assets', 46),
  (4, 'Who Did the Shoot — How to buy it', '- Book a date: https://matthew.mccluster.org/pay.html?offer=booking-deposit
Or start from the cards at https://matthew.mccluster.org/sites.html', 36)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#who-did-the-shoot';

-- Write a Song (Write a Song Campaign) (6 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'offer', 'https://matthew.mccluster.org/sites.html#write-a-song', 'Write a Song (Write a Song Campaign)', 'The highest-level cultural campaign. An original song built into a rollout, not a jingle purchase.

## Price
From $525 per campaign.
- Custom scoring: $525 — from · per finished minute
- Sync license: $875 — from · web · one year · non-exclusive
- Jingle · brand anthem: $1,690 — from · written, produced, yours
- Full creative campaign: $15,750 — flat · one campaign end to end

## Equity Uprise price
Equity terms structured during discovery.

## What is included
- Original jingle creation
- Songwriting
- Music-production coordination
- Campaign concept and brand story
- Short-form campaign assets
- Social rollout
- Release planning
- Reporting

## Never promised
These are not offered and must never be implied:
- Guaranteed virality
- Guaranteed views
- Guaranteed sales
- Guaranteed influencer participation
- Guaranteed platform placement

## How to buy it
- Start discovery: https://matthew.mccluster.org/pay.html?offer=booking-deposit
Or start from the cards at https://matthew.mccluster.org/sites.html
', 'ledger', '1015:c3f3f6a3', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#write-a-song';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Write a Song (Write a Song Campaign)', 'The highest-level cultural campaign. An original song built into a rollout, not a jingle purchase.', 25),
  (1, 'Write a Song (Write a Song Campaign) — Price', 'From $525 per campaign.
- Custom scoring: $525 — from · per finished minute
- Sync license: $875 — from · web · one year · non-exclusive
- Jingle · brand anthem: $1,690 — from · written, produced, yours
- Full creative campaign: $15,750 — flat · one campaign end to end', 68),
  (2, 'Write a Song (Write a Song Campaign) — Equity Uprise price', 'Equity terms structured during discovery.', 11),
  (3, 'Write a Song (Write a Song Campaign) — What is included', '- Original jingle creation
- Songwriting
- Music-production coordination
- Campaign concept and brand story
- Short-form campaign assets
- Social rollout
- Release planning
- Reporting', 46),
  (4, 'Write a Song (Write a Song Campaign) — Never promised', 'These are not offered and must never be implied:
- Guaranteed virality
- Guaranteed views
- Guaranteed sales
- Guaranteed influencer participation
- Guaranteed platform placement', 45),
  (5, 'Write a Song (Write a Song Campaign) — How to buy it', '- Start discovery: https://matthew.mccluster.org/pay.html?offer=booking-deposit
Or start from the cards at https://matthew.mccluster.org/sites.html', 37)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offer' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#write-a-song';

-- Everything that can be paid for online (3 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'offering', 'https://matthew.mccluster.org/sites.html', 'Everything that can be paid for online', 'These are the exact things a card can be charged for on this site today.
Every one of them opens a Stripe checkout. Nothing else can be paid for online;
anything not on this list is arranged through the questions at /onboard.html.

## The list
- 5×7 print — $15 — https://matthew.mccluster.org/pay.html?offer=print-5x7
- 8×10 print — $25 — https://matthew.mccluster.org/pay.html?offer=print-8x10
- 11×14 print — $40 — https://matthew.mccluster.org/pay.html?offer=print-11x14
- 16×20 print — $55 — https://matthew.mccluster.org/pay.html?offer=print-16x20
- 24×36 print — $85 — https://matthew.mccluster.org/pay.html?offer=print-24x36
- PNG · personal use — $15 — https://matthew.mccluster.org/pay.html?offer=file-png
- Full-res + print rights — $40 — https://matthew.mccluster.org/pay.html?offer=file-fullres
- RAW + license — $250 — https://matthew.mccluster.org/pay.html?offer=file-raw
- Booking deposit — you choose, $100 to $10,000 — https://matthew.mccluster.org/pay.html?offer=booking-deposit
- Approved invoice — you choose, $25 to $25,000 — https://matthew.mccluster.org/pay.html?offer=approved-invoice
- The Mission Fund — you choose, $5 to $25,000 — https://matthew.mccluster.org/pay.html?offer=mission-fund-donation
- Start the draft — $33 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-deposit
- Go live: domain and first month — $66 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-start
- Go live: domain and the year of hosting — $393 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-year
- Hosting, by the year — $360 — https://matthew.mccluster.org/pay.html?offer=hosting-year
- Hosting — $33 — https://matthew.mccluster.org/pay.html?offer=hosting-monthly
- Domain renewal — $33 — https://matthew.mccluster.org/pay.html?offer=domain-renewal
- Anti-Social Management — $875 — https://matthew.mccluster.org/pay.html?offer=anti-social-m
', 'ledger', '1891:b4e17665', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offering'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Everything that can be paid for online', 'These are the exact things a card can be charged for on this site today.
Every one of them opens a Stripe checkout. Nothing else can be paid for online;
anything not on this list is arranged through the questions at /onboard.html.', 58),
  (1, 'Everything that can be paid for online — The list', '- 5×7 print — $15 — https://matthew.mccluster.org/pay.html?offer=print-5x7
- 8×10 print — $25 — https://matthew.mccluster.org/pay.html?offer=print-8x10
- 11×14 print — $40 — https://matthew.mccluster.org/pay.html?offer=print-11x14
- 16×20 print — $55 — https://matthew.mccluster.org/pay.html?offer=print-16x20
- 24×36 print — $85 — https://matthew.mccluster.org/pay.html?offer=print-24x36
- PNG · personal use — $15 — https://matthew.mccluster.org/pay.html?offer=file-png
- Full-res + print rights — $40 — https://matthew.mccluster.org/pay.html?offer=file-fullres
- RAW + license — $250 — https://matthew.mccluster.org/pay.html?offer=file-raw
- Booking deposit — you choose, $100 to $10,000 — https://matthew.mccluster.org/pay.html?offer=booking-deposit
- Approved invoice — you choose, $25 to $25,000 — https://matthew.mccluster.org/pay.html?offer=approved-invoice
- The Mission Fund — you choose, $5 to $25,000 — https://matthew.mccluster.org/pay.html?offer=mission-fund-donation
- Start the draft — $33 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-deposit
- Go live: domain and first month — $66 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-start
- Go live: domain and the year of hosting — $393 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-year
- Hosting, by the year — $360 — https://matthew.mccluster.org/pay.html?offer=hosting-year
- Hosting', 350),
  (2, 'Everything that can be paid for online — The list', 'and the year of hosting — $393 — https://matthew.mccluster.org/pay.html?offer=domain-hosting-year
- Hosting, by the year — $360 — https://matthew.mccluster.org/pay.html?offer=hosting-year
- Hosting

— $33 — https://matthew.mccluster.org/pay.html?offer=hosting-monthly
- Domain renewal — $33 — https://matthew.mccluster.org/pay.html?offer=domain-renewal
- Anti-Social Management — $875 — https://matthew.mccluster.org/pay.html?offer=anti-social-m', 112)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'offering' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html';

-- How the website build works (5 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'service', 'https://matthew.mccluster.org/sites.html#build', 'How the website build works', 'The website itself is built for free. What is paid for is the domain and the
hosting: the address people type, and the machine that answers when they do.

## What free actually means
The build is included. There is no setup fee, no design fee and no per-page
charge. What is billed is the address and the ground it sits on.

## The order things happen in
1. Pick the address on the domain and hosting card at https://matthew.mccluster.org/sites.html and check it is free.
2. Pay to go live. The chosen name travels with the payment.
3. The draft gets built and sent for review.
4. Changes get made until it is right.
5. It goes live on the address.

## Drafts
Buying the domain puts you on a draft a month: one round of changes a month,
included, for as long as the hosting is running.

## Who does the work
Matthew McCluster, McCluster Corp. One person who builds it and one desk that
runs it — not an agency handing the work down a chain.
', 'ledger', '941:a87f3b97', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'service'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#build';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'How the website build works', 'The website itself is built for free. What is paid for is the domain and the
hosting: the address people type, and the machine that answers when they do.', 39),
  (1, 'How the website build works — What free actually means', 'The build is included. There is no setup fee, no design fee and no per-page
charge. What is billed is the address and the ground it sits on.', 35),
  (2, 'How the website build works — The order things happen in', '1. Pick the address on the domain and hosting card at https://matthew.mccluster.org/sites.html and check it is free.
2. Pay to go live. The chosen name travels with the payment.
3. The draft gets built and sent for review.
4. Changes get made until it is right.
5. It goes live on the address.', 74),
  (3, 'How the website build works — Drafts', 'Buying the domain puts you on a draft a month: one round of changes a month,
included, for as long as the hosting is running.', 32),
  (4, 'How the website build works — Who does the work', 'Matthew McCluster, McCluster Corp. One person who builds it and one desk that
runs it — not an agency handing the work down a chain.', 33)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'service' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#build';

-- Domain names: checking one and buying one (5 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'service', 'https://matthew.mccluster.org/sites.html#domains', 'Domain names: checking one and buying one', '## Is a name available
Type it into the domain and hosting card at https://matthew.mccluster.org/sites.html and press
Check. It asks the registries directly and answers straight away whether that
address is available or already taken, and what it costs. Availability is
checked live; nobody has to look it up for you and there is nothing to wait
for.

## Which endings can be bought in one tap
.com, .net and .org. Each is $33 for the year.

## Other endings
.io, .co, .dev, .app, .me, .info, .biz, .us, .church, .tv and .xyz can all be
looked up and can all be registered — they are just priced with you first,
because they do not all cost the same as a .com. Ask and a price comes back.

## Checking does not hold a name
A search says the address was available at the moment it was asked. Nothing
is reserved until it is registered, and it is registered once the payment
lands. An address that was available an hour ago can be taken by somebody
else, so the answer is never a promise.

## Renewal
The domain renews at $33 a year.
', 'ledger', '1032:e1a31913', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'service'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#domains';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Domain names: checking one and buying one — Is a name available', 'Type it into the domain and hosting card at https://matthew.mccluster.org/sites.html and press
Check. It asks the registries directly and answers straight away whether that
address is available or already taken, and what it costs. Availability is
checked live; nobody has to look it up for you and there is nothing to wait
for.', 82),
  (1, 'Domain names: checking one and buying one — Which endings can be bought in one tap', '.com, .net and .org. Each is $33 for the year.', 12),
  (2, 'Domain names: checking one and buying one — Other endings', '.io, .co, .dev, .app, .me, .info, .biz, .us, .church, .tv and .xyz can all be
looked up and can all be registered — they are just priced with you first,
because they do not all cost the same as a .com. Ask and a price comes back.', 58),
  (3, 'Domain names: checking one and buying one — Checking does not hold a name', 'A search says the address was available at the moment it was asked. Nothing
is reserved until it is registered, and it is registered once the payment
lands. An address that was available an hour ago can be taken by somebody
else, so the answer is never a promise.', 66),
  (4, 'Domain names: checking one and buying one — Renewal', 'The domain renews at $33 a year.', 8)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'service' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#domains';

-- What hosting includes and what it costs (4 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'service', 'https://matthew.mccluster.org/sites.html#hosting', 'What hosting includes and what it costs', '## The monthly rate
$33 a month, every month after the first. The first
month is already inside the go-live total, so month one is never billed twice.

## Paying the year together
$30 a month instead of $33,
when the twelve months are paid together. That is $360
for the year of hosting, or $393 to go live including the
domain, and it saves $36 against paying monthly.

## What is in it
- The machine that answers when somebody types the address
- SSL, so the address loads as https and browsers do not warn people off
- Backups
- Keeping it online

## No revenue share
Domain and hosting has no Equity Uprise version and takes no percentage of
anything. It is an address and a machine, billed like plumbing.
', 'ledger', '710:9dc31262', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'service'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#hosting';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'What hosting includes and what it costs — The monthly rate', '$33 a month, every month after the first. The first
month is already inside the go-live total, so month one is never billed twice.', 33),
  (1, 'What hosting includes and what it costs — Paying the year together', '$30 a month instead of $33,
when the twelve months are paid together. That is $360
for the year of hosting, or $393 to go live including the
domain, and it saves $36 against paying monthly.', 48),
  (2, 'What hosting includes and what it costs — What is in it', '- The machine that answers when somebody types the address
- SSL, so the address loads as https and browsers do not warn people off
- Backups
- Keeping it online', 41),
  (3, 'What hosting includes and what it costs — No revenue share', 'Domain and hosting has no Equity Uprise version and takes no percentage of
anything. It is an address and a machine, billed like plumbing.', 35)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'service' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#hosting';

-- Equity Uprise: paying with a share of revenue instead of cash (5 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'program', 'https://matthew.mccluster.org/sites-details.html#equity', 'Equity Uprise: paying with a share of revenue instead of cash', 'No stock. No membership interest. No ownership. Equity Uprise is a time-limited revenue-share agreement. Revenue sharing ends at the earlier of the stated term or the stated cap, whichever comes first. The domain is always paid separately, up front. Participation requires a program-fit review and a signed agreement.

## What it is
Half the standard monthly price, against a capped share of the revenue the
work actually brings in. It is a payment arrangement, not an investment: no
ownership is taken and no equity in the company changes hands, whatever the
name suggests.

## The numbers on Anti-Social
$437.50 a month, plus 50% of approved eligible connected online revenue, for up to 12 months, ending at the earlier of the term or a $105,000 cap.

## Which services have it
Anti-Social has an approved Equity Uprise rate. Who Did the Shoot and Write a
Song are quoted per project, so an arrangement for those is written during
discovery and there is no standing formula. Domain and hosting has none at all.

## It is an agreement, not a button
Equity Uprise cannot be bought in a tap because it is a contract. It starts at
https://matthew.mccluster.org/onboard.html and the terms are written down before anything begins.
', 'ledger', '1227:14609146', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'program'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites-details.html#equity';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Equity Uprise: paying with a share of revenue instead of cash', 'No stock. No membership interest. No ownership. Equity Uprise is a time-limited revenue-share agreement. Revenue sharing ends at the earlier of the stated term or the stated cap, whichever comes first. The domain is always paid separately, up front. Participation requires a program-fit review and a signed agreement.', 80),
  (1, 'Equity Uprise: paying with a share of revenue instead of cash — What it is', 'Half the standard monthly price, against a capped share of the revenue the
work actually brings in. It is a payment arrangement, not an investment: no
ownership is taken and no equity in the company changes hands, whatever the
name suggests.', 61),
  (2, 'Equity Uprise: paying with a share of revenue instead of cash — The numbers on Anti-Social', '$437.50 a month, plus 50% of approved eligible connected online revenue, for up to 12 months, ending at the earlier of the term or a $105,000 cap.', 37),
  (3, 'Equity Uprise: paying with a share of revenue instead of cash — Which services have it', 'Anti-Social has an approved Equity Uprise rate. Who Did the Shoot and Write a
Song are quoted per project, so an arrangement for those is written during
discovery and there is no standing formula. Domain and hosting has none at all.', 58),
  (4, 'Equity Uprise: paying with a share of revenue instead of cash — It is an agreement, not a button', 'Equity Uprise cannot be bought in a tap because it is a contract. It starts at
https://matthew.mccluster.org/onboard.html and the terms are written down before anything begins.', 44)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'program' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites-details.html#equity';

-- Common questions (8 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'faq', 'https://matthew.mccluster.org/sites.html#faq', 'Common questions', '## How much is a website
The build is free. Going live is $66 — $33 for the
domain for a year and $33 for the first month of
hosting — then $33 a month. Or $393
to go live with the whole year of hosting paid, which drops the monthly rate to
$30.

## Do you take a cut of my sales
Not on domain and hosting. Never. That one is a flat rate.
On Anti-Social there is an optional Equity Uprise arrangement, and it is optional.

## How long does it take
It starts when the payment lands and the draft comes back for review. A real
timeline depends on how ready the words and pictures are, which is one of the
questions asked at https://matthew.mccluster.org/onboard.html.

## Can I keep my own domain
Yes. Point it at the hosting and keep it. The domain line is only for
registering a new one.

## Do you do social media as well
Yes — that is Anti-Social. Website and socials run as one service rather than
two products.

## Do you do photography and video
Yes — that is Who Did the Shoot. Priced per project, per day or per event.

## Where do I actually pay
https://matthew.mccluster.org/sites.html — four cards, one price and one button each.

## Can I see something you built
https://matthew.mccluster.org/sites.html has the client examples, and each one opens the real site.
', 'ledger', '1274:1f7770d2', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'faq'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#faq';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Common questions — How much is a website', 'The build is free. Going live is $66 — $33 for the
domain for a year and $33 for the first month of
hosting — then $33 a month. Or $393
to go live with the whole year of hosting paid, which drops the monthly rate to
$30.', 55),
  (1, 'Common questions — Do you take a cut of my sales', 'Not on domain and hosting. Never. That one is a flat rate.
On Anti-Social there is an optional Equity Uprise arrangement, and it is optional.', 36),
  (2, 'Common questions — How long does it take', 'It starts when the payment lands and the draft comes back for review. A real
timeline depends on how ready the words and pictures are, which is one of the
questions asked at https://matthew.mccluster.org/onboard.html.', 55),
  (3, 'Common questions — Can I keep my own domain', 'Yes. Point it at the hosting and keep it. The domain line is only for
registering a new one.', 23),
  (4, 'Common questions — Do you do social media as well', 'Yes — that is Anti-Social. Website and socials run as one service rather than
two products.', 23),
  (5, 'Common questions — Do you do photography and video', 'Yes — that is Who Did the Shoot. Priced per project, per day or per event.', 19),
  (6, 'Common questions — Where do I actually pay', 'https://matthew.mccluster.org/sites.html — four cards, one price and one button each.', 22),
  (7, 'Common questions — Can I see something you built', 'https://matthew.mccluster.org/sites.html has the client examples, and each one opens the real site.', 25)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'faq' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#faq';

-- What this work costs everywhere else (14 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'market', 'https://matthew.mccluster.org/sites.html#market', 'What this work costs everywhere else', 'At least a third below what this work costs around here. True of every line, because any line that was not true of was moved until it was.

Ranges published in 2026 pricing guides for small-business work in these markets and nationally. They are NOT quotes from named local companies, they are NOT what any particular competitor charges, and they must never be presented as either.

Checked 2026-08-29 for New Haven, Connecticut and Atlanta, Georgia.
These are the figures as of the date checked. Market rates move; if the checked date is more than six months old, say the number is from a guide rather than from this week.

## The discount, in one line
Nothing here costs more than 67% of the market median for the same work. The ceiling is a CEILING and not a target: a price already below it is left alone rather than raised up to it. Raising the cheap end to hit a discount number exactly would put the price up on the people this discount exists to reach, and would end the free build, which is the hook the whole offer rests on.

## A small-business website, built
Everywhere else: $1,500 to $8,000 one-time.
Here: free — the build is included, not billed.
That line is not charged at all here.
A third off that median is $2,345, which is the most this may cost.
Freelancers $1,500–$8,000. Agencies $5,000–$30,000. A basic site for a local service business in New Haven starts around $1,500–$4,500; Atlanta small-business projects land $2,000–$10,000.

## Hosting and maintenance
Everywhere else: $50 to $500 per month.
Here: $33 a month.
That is below the bottom of the band.
A third off that median is $100.50, which is the most this may cost.
Freelancers $50–$200/mo. Agencies $150–$500/mo. Connecticut packages commonly $50–$325/mo. Yearly, that is $1,000–$6,000 for a small-business site.

## Social media management, on its own
Everywhere else: $500 to $4,000 per month.
Here: $875 a month — and that runs the WEBSITE as well as the feeds.
That sits inside the band rather than under it.
A third off that median is $1,005, which is the most this may cost.
44% of small businesses spend $500–$2,000/mo. Boutique agencies $1,000–$4,000/mo for two or three platforms. Full done-for-you work commonly $2,500/mo. This band is for SOCIAL ALONE, with no website management in it.

## A professional headshot session
Everywhere else: $500 to $1,500 the session.
Here: $285.
That is below the bottom of the band.
A third off that median is $502.50, which is the most this may cost.
One to two hours, three to ten retouched images.

## Event photography
Everywhere else: $150 to $500 per hour.
Here: $201 an hour.
That sits inside the band rather than under it.
A third off that median is $201, which is the most this may cost.
Event photographers charge $150-$500 an hour. This rate was $310 — inside the band rather than under it — until the golden discount was applied; it is now at the ceiling.

## A photography half-day
Everywhere else: $800 to $2,000 up to four or five hours.
Here: $938.
That sits inside the band rather than under it.
A third off that median is $938, which is the most this may cost.
For smaller projects a half-day of four to five hours runs $800-$2,000. This rate was $2,210, ABOVE the band, until the golden discount brought it to the ceiling. It is the one price on this list that had to come down rather than already being under.

## A photography full day
Everywhere else: $1,500 to $4,000 eight hours.
Here: $1,842.50.
That sits inside the band rather than under it.
A third off that median is $1,842.50, which is the most this may cost.
A full day runs $1,500-$4,000 for smaller projects. Experienced commercial and advertising photographers run $3,000-$10,000 for the photographer alone, before studio, models, styling or retouching.

## A produced video day
Everywhere else: $1,500 to $8,000 eight hours, crew and kit.
A third off that median is $2,010, which is the most this may cost.
Compared against the PRODUCED tier, not a bare freelance videographer at $600-$1,200 a day, because these days include the kit, the crew and the edit. A minimal five-person crew starts near $2,400 for one shoot day; a full crew is $3,000-$8,000.

## A produced video half-day
Everywhere else: $900 to $4,800 up to five hours.
A third off that median is $1,206, which is the most this may cost.
Half-days run 60-70% of a full day rather than half, which is why the band is not simply the day band halved.

## A music video
Everywhere else: $2,000 to $30,000 one day, one location.
A third off that median is $3,350, which is the most this may cost.
Shoestring shoots $2,000-$5,000. A professionally produced music video averages $5,000-$30,000. Commercial productions go far past that and are not the comparison here.

## A brand film
Everywhere else: $15,000 to $50,000 shoot and edit.
A third off that median is $13,400, which is the most this may cost.
A produced 60-second brand video runs $15,000-$75,000; brand films and multi-day productions $20,000-$50,000.

## How to use these numbers
- State the band, then state the McCluster price, and stop. Let them do the subtraction.
- Never say ''cheaper than everyone'' or ''the lowest price''. Some of these prices are not below the band, and a claim that is wrong once is a claim nobody believes again.
- Never name a competitor and never attribute a price to one.
- A band is a band. Do not quote the midpoint as if it were a fact about a specific business.
', 'ledger', '5433:bb65d449', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'market'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#market';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'What this work costs everywhere else', 'At least a third below what this work costs around here. True of every line, because any line that was not true of was moved until it was.

Ranges published in 2026 pricing guides for small-business work in these markets and nationally. They are NOT quotes from named local companies, they are NOT what any particular competitor charges, and they must never be presented as either.

Checked 2026-08-29 for New Haven, Connecticut and Atlanta, Georgia.
These are the figures as of the date checked. Market rates move; if the checked date is more than six months old, say the number is from a guide rather than from this week.', 156),
  (1, 'What this work costs everywhere else — The discount, in one line', 'Nothing here costs more than 67% of the market median for the same work. The ceiling is a CEILING and not a target: a price already below it is left alone rather than raised up to it. Raising the cheap end to hit a discount number exactly would put the price up on the people this discount exists to reach, and would end the free build, which is the hook the whole offer rests on.', 95),
  (2, 'What this work costs everywhere else — A small-business website, built', 'Everywhere else: $1,500 to $8,000 one-time.
Here: free — the build is included, not billed.
That line is not charged at all here.
A third off that median is $2,345, which is the most this may cost.
Freelancers $1,500–$8,000. Agencies $5,000–$30,000. A basic site for a local service business in New Haven starts around $1,500–$4,500; Atlanta small-business projects land $2,000–$10,000.', 97),
  (3, 'What this work costs everywhere else — Hosting and maintenance', 'Everywhere else: $50 to $500 per month.
Here: $33 a month.
That is below the bottom of the band.
A third off that median is $100.50, which is the most this may cost.
Freelancers $50–$200/mo. Agencies $150–$500/mo. Connecticut packages commonly $50–$325/mo. Yearly, that is $1,000–$6,000 for a small-business site.', 79),
  (4, 'What this work costs everywhere else — Social media management, on its own', 'Everywhere else: $500 to $4,000 per month.
Here: $875 a month — and that runs the WEBSITE as well as the feeds.
That sits inside the band rather than under it.
A third off that median is $1,005, which is the most this may cost.
44% of small businesses spend $500–$2,000/mo. Boutique agencies $1,000–$4,000/mo for two or three platforms. Full done-for-you work commonly $2,500/mo. This band is for SOCIAL ALONE, with no website management in it.', 111),
  (5, 'What this work costs everywhere else — A professional headshot session', 'Everywhere else: $500 to $1,500 the session.
Here: $285.
That is below the bottom of the band.
A third off that median is $502.50, which is the most this may cost.
One to two hours, three to ten retouched images.', 53),
  (6, 'What this work costs everywhere else — Event photography', 'Everywhere else: $150 to $500 per hour.
Here: $201 an hour.
That sits inside the band rather than under it.
A third off that median is $201, which is the most this may cost.
Event photographers charge $150-$500 an hour. This rate was $310 — inside the band rather than under it — until the golden discount was applied; it is now at the ceiling.', 86),
  (7, 'What this work costs everywhere else — A photography half-day', 'Everywhere else: $800 to $2,000 up to four or five hours.
Here: $938.
That sits inside the band rather than under it.
A third off that median is $938, which is the most this may cost.
For smaller projects a half-day of four to five hours runs $800-$2,000. This rate was $2,210, ABOVE the band, until the golden discount brought it to the ceiling. It is the one price on this list that had to come down rather than already being under.', 109),
  (8, 'What this work costs everywhere else — A photography full day', 'Everywhere else: $1,500 to $4,000 eight hours.
Here: $1,842.50.
That sits inside the band rather than under it.
A third off that median is $1,842.50, which is the most this may cost.
A full day runs $1,500-$4,000 for smaller projects. Experienced commercial and advertising photographers run $3,000-$10,000 for the photographer alone, before studio, models, styling or retouching.', 95),
  (9, 'What this work costs everywhere else — A produced video day', 'Everywhere else: $1,500 to $8,000 eight hours, crew and kit.
A third off that median is $2,010, which is the most this may cost.
Compared against the PRODUCED tier, not a bare freelance videographer at $600-$1,200 a day, because these days include the kit, the crew and the edit. A minimal five-person crew starts near $2,400 for one shoot day; a full crew is $3,000-$8,000.', 94),
  (10, 'What this work costs everywhere else — A produced video half-day', 'Everywhere else: $900 to $4,800 up to five hours.
A third off that median is $1,206, which is the most this may cost.
Half-days run 60-70% of a full day rather than half, which is why the band is not simply the day band halved.', 57),
  (11, 'What this work costs everywhere else — A music video', 'Everywhere else: $2,000 to $30,000 one day, one location.
A third off that median is $3,350, which is the most this may cost.
Shoestring shoots $2,000-$5,000. A professionally produced music video averages $5,000-$30,000. Commercial productions go far past that and are not the comparison here.', 74),
  (12, 'What this work costs everywhere else — A brand film', 'Everywhere else: $15,000 to $50,000 shoot and edit.
A third off that median is $13,400, which is the most this may cost.
A produced 60-second brand video runs $15,000-$75,000; brand films and multi-day productions $20,000-$50,000.', 58),
  (13, 'What this work costs everywhere else — How to use these numbers', '- State the band, then state the McCluster price, and stop. Let them do the subtraction.
- Never say ''cheaper than everyone'' or ''the lowest price''. Some of these prices are not below the band, and a claim that is wrong once is a claim nobody believes again.
- Never name a competitor and never attribute a price to one.
- A band is a band. Do not quote the midpoint as if it were a fact about a specific business.', 104)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'market' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#market';

-- Who qualifies for Equity Uprise (5 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'program', 'https://matthew.mccluster.org/sites-details.html#equity-eligibility', 'Who qualifies for Equity Uprise', 'To qualify: the website is one we built, your traffic runs through it, and payments run on the rails we connect. That is what makes the revenue countable, and the whole arrangement is priced off a count.

## What you need, and why
- The website has to be one we built. The revenue share is calculated from what the site brings in. On a site somebody else built and hosts, we cannot see the orders, cannot verify a total, and would be asking the customer to self-report the number their own bill is based on. That is not a term either side should accept.
- The connected traffic has to run through that website. A link in a bio that goes straight to a third-party checkout is a sale the site never sees. The share is on CONNECTED revenue, and traffic routed around the site is revenue nobody can connect - which ends in an argument about a number instead of a business getting built.
- Payments have to run on the rails we connect for you. This is the meter. It is what turns ''eligible connected revenue'' from a phrase in an agreement into a figure both sides can read off the same screen on the same day.

## If that is not you
A business that wants to keep its existing site, or send its buyers somewhere else to pay, can still work with us - at the standard price, with no revenue share and nothing to measure. That is M Mode, and it is not a lesser door.

## What the discount is
Half the standard monthly price — $437.50 a month on Anti-Social instead of $875, against a capped share of the revenue the work brings in.
It is a payment arrangement. No ownership changes hands.

## It is not automatic
Meeting the three requirements makes somebody ELIGIBLE. It still takes a programme-fit review and a signed agreement, and it is never preselected for anybody. Do not tell somebody they are approved.
', 'ledger', '1803:cfa921ef', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'program'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites-details.html#equity-eligibility';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Who qualifies for Equity Uprise', 'To qualify: the website is one we built, your traffic runs through it, and payments run on the rails we connect. That is what makes the revenue countable, and the whole arrangement is priced off a count.', 51),
  (1, 'Who qualifies for Equity Uprise — What you need, and why', '- The website has to be one we built. The revenue share is calculated from what the site brings in. On a site somebody else built and hosts, we cannot see the orders, cannot verify a total, and would be asking the customer to self-report the number their own bill is based on. That is not a term either side should accept.
- The connected traffic has to run through that website. A link in a bio that goes straight to a third-party checkout is a sale the site never sees. The share is on CONNECTED revenue, and traffic routed around the site is revenue nobody can connect - which ends in an argument about a number instead of a business getting built.
- Payments have to run on the rails we connect for you. This is the meter. It is what turns ''eligible connected revenue'' from a phrase in an agreement into a figure both sides can read off the same screen on the same day.', 219),
  (2, 'Who qualifies for Equity Uprise — If that is not you', 'A business that wants to keep its existing site, or send its buyers somewhere else to pay, can still work with us - at the standard price, with no revenue share and nothing to measure. That is M Mode, and it is not a lesser door.', 58),
  (3, 'Who qualifies for Equity Uprise — What the discount is', 'Half the standard monthly price — $437.50 a month on Anti-Social instead of $875, against a capped share of the revenue the work brings in.
It is a payment arrangement. No ownership changes hands.', 49),
  (4, 'Who qualifies for Equity Uprise — It is not automatic', 'Meeting the three requirements makes somebody ELIGIBLE. It still takes a programme-fit review and a signed agreement, and it is never preselected for anybody. Do not tell somebody they are approved.', 50)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'program' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites-details.html#equity-eligibility';

-- Who McCluster is (3 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'about', 'https://matthew.mccluster.org', 'Who McCluster is', 'McCluster Corp. Matthew McCluster builds the websites, runs the hosting and
runs the desk.

## What is sold
Four things: domain and hosting, Anti-Social (website and social management as
one service), Who Did the Shoot (photography and video), and Write a Song
(original music built into a campaign).

## Where things live
- Everything for sale: https://matthew.mccluster.org/sites.html
- The long version, with the full terms: https://matthew.mccluster.org/sites-details.html
- The questions, to start anything that is not a one-tap purchase: https://matthew.mccluster.org/onboard.html
- Equity Uprise, the civic programme: https://matthew.mccluster.org/equity-uprise.html
- The music: https://matthew.mccluster.org/album.html
', 'ledger', '728:6a2deea7', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'about'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Who McCluster is', 'McCluster Corp. Matthew McCluster builds the websites, runs the hosting and
runs the desk.', 23),
  (1, 'Who McCluster is — What is sold', 'Four things: domain and hosting, Anti-Social (website and social management as
one service), Who Did the Shoot (photography and video), and Write a Song
(original music built into a campaign).', 48),
  (2, 'Who McCluster is — Where things live', '- Everything for sale: https://matthew.mccluster.org/sites.html
- The long version, with the full terms: https://matthew.mccluster.org/sites-details.html
- The questions, to start anything that is not a one-tap purchase: https://matthew.mccluster.org/onboard.html
- Equity Uprise, the civic programme: https://matthew.mccluster.org/equity-uprise.html
- The music: https://matthew.mccluster.org/album.html', 101)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'about' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org';

-- Sites already built (2 chunks)
insert into public.kb_documents (org_id, kind, url, title, body, source, content_hash, enabled)
select o.id, 'proof', 'https://matthew.mccluster.org/sites.html#examples', 'Sites already built', 'Real clients with real sites. Each one opens.

## The list
- Shiloh Baptist Church (The app) — An installable church app: service times, a prayer wall, events with RSVPs, giving, and a live stream. — https://matthew.mccluster.org/demo.html?s=shiloh
- Yohana Robertson (The lead engine) — A Bridgeport real estate agent with no listings yet, so the site is built to win them: rental enquiries, landlords and prospective sellers captured and followed up, with the listings shelf dark until there is something to put on it. — https://matthew.mccluster.org/demo.html?s=yohana
', 'ledger', '572:2c4102a1', true
  from public.orgs o where o.slug = 'mccluster'
on conflict (org_id, kind, coalesce(url, title)) do update
  set title = excluded.title, body = excluded.body,
      content_hash = excluded.content_hash, enabled = true, updated_at = now();

delete from public.kb_chunks c using public.kb_documents d, public.orgs o
 where c.document_id = d.id and d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'proof'
   and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#examples';

insert into public.kb_chunks (document_id, ordinal, heading, body, tokens)
select d.id, v.ordinal, v.heading, v.body, v.tokens from public.kb_documents d, public.orgs o,
(values
  (0, 'Sites already built', 'Real clients with real sites. Each one opens.', 12),
  (1, 'Sites already built — The list', '- Shiloh Baptist Church (The app) — An installable church app: service times, a prayer wall, events with RSVPs, giving, and a live stream. — https://matthew.mccluster.org/demo.html?s=shiloh
- Yohana Robertson (The lead engine) — A Bridgeport real estate agent with no listings yet, so the site is built to win them: rental enquiries, landlords and prospective sellers captured and followed up, with the listings shelf dark until there is something to put on it. — https://matthew.mccluster.org/demo.html?s=yohana', 128)
) as v(ordinal, heading, body, tokens)
 where d.org_id = o.id and o.slug = 'mccluster'
   and d.kind = 'proof' and coalesce(d.url, d.title) = 'https://matthew.mccluster.org/sites.html#examples';

commit;
