// Music supply-chain control surface for Equity Uprise/McCluster releases.
// Metadata preparation is editable; DDEX delivery is bound to a high-risk
// approval over the exact release/recipient payload.
import { authorize, cors, db, emitEvent, json, orgBySlug, safeText, sha256Hex, verifyCaller } from "../_shared/eu-policy-os.ts";

async function release(orgId:string,id:unknown){const sid=safeText(id,80);const r=(await db(`eu_releases?id=eq.${encodeURIComponent(sid)}&org_id=eq.${orgId}&select=*&limit=1`))?.[0];if(!r)throw new Error("release not found");return r;}
async function context(orgId:string,id:unknown){const r=await release(orgId,id);const tracks=await db(`eu_release_tracks?release_id=eq.${r.id}&select=*,eu_recordings(*)&order=disc_no.asc,track_no.asc`);const splits=await db(`eu_rights_splits?org_id=eq.${orgId}&resource_id=eq.${r.id}&resource_type=eq.release&select=*`);return{release:r,tracks:tracks??[],splits:splits??[]};}
function preflight(c:any){const gaps:any[]=[];const r=c.release;if(!r.title)gaps.push({field:"title"});if(!r.artist)gaps.push({field:"artist"});if(!r.upc)gaps.push({field:"upc"});if(!r.release_date)gaps.push({field:"release_date"});if(!c.tracks.length)gaps.push({field:"tracks"});for(const t of c.tracks){const x=t.eu_recordings;if(!x?.isrc)gaps.push({field:"isrc",track:t.track_no});if(!x?.title)gaps.push({field:"track_title",track:t.track_no});if(!x?.artist)gaps.push({field:"track_artist",track:t.track_no});if(!x?.master_owner)gaps.push({field:"master_owner",track:t.track_no});}const byType=new Map<string,number>();for(const s of c.splits)byType.set(s.rights_type||s.role,(byType.get(s.rights_type||s.role)||0)+Number(s.share_bps||0));const invalid=[...byType].filter(([,bps])=>bps!==10000);return{ready:gaps.length===0&&invalid.length===0,gaps,rights_totals:Object.fromEntries(byType),rights_invalid:invalid.map(([type,bps])=>({type,share_bps:bps}))};}
async function deliveryHash(c:any,body:any){return sha256Hex(JSON.stringify({release_id:c.release.id,upc:c.release.upc,title:c.release.title,artist:c.release.artist,release_date:c.release.release_date,tracks:c.tracks.map((t:any)=>({disc:t.disc_no,track:t.track_no,isrc:t.eu_recordings?.isrc,title:t.eu_recordings?.title,artist:t.eu_recordings?.artist,master_owner:t.eu_recordings?.master_owner})),recipient_dpid:safeText(body.recipient_dpid,120),recipient_name:safeText(body.recipient_name,200),endpoint:safeText(body.endpoint,1000)}));}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const caller=await verifyCaller(req);if(!caller)return json({error:"authentication required"},401);try{const org=await orgBySlug("mccluster");const body=await req.json();const action=safeText(body.action,60);
 if(action==="preflight"){
   const d=await authorize(caller,org.id,"research.read");if(!d.allowed)return json({error:"permission required"},403);const c=await context(org.id,body.release_id);return json({ok:true,...preflight(c),release:c.release,tracks:c.tracks.length});
 }
 if(action==="create-release"){
   const d=await authorize(caller,org.id,"research.write");if(!d.allowed)return json({error:"permission required"},403);const title=safeText(body.title,500);if(!title)return json({error:"title required"},400);const r=(await db("eu_releases",{method:"POST",body:JSON.stringify({org_id:org.id,initiative_id:safeText(body.initiative_id,80)||null,title,artist:safeText(body.artist,300),upc:safeText(body.upc,80),release_type:safeText(body.release_type,30)||"single",release_date:body.release_date||null,label:safeText(body.label,300)||"McCluster Corp",territories:Array.isArray(body.territories)?body.territories.slice(0,100):["Worldwide"],artwork_ref:body.artwork_ref||{},status:"draft",metadata:body.metadata&&typeof body.metadata==="object"?body.metadata:{}})}))?.[0];await emitEvent({orgId:org.id,initiativeId:r.initiative_id,eventType:"music.release.created",entityType:"eu_releases",entityId:r.id,actorMUid:caller.mUid,actorUserId:caller.authUserId,data:{title:r.title,upc:r.upc}});return json({ok:true,release:r});
 }
 if(action==="deliver-ddex"){
   const c=await context(org.id,body.release_id);const ready=preflight(c);if(!ready.ready)return json({ok:false,ready:false,...ready},409);const requestHash=await deliveryHash(c,body);const decision=await authorize(caller,org.id,"music.deliver",{resourceType:"eu_releases",resourceId:c.release.id,requestHash,approvalId:safeText(body.approval_id,80)});if(!decision.allowed)return json({ok:false,approval_required:true,reason:decision.reason,request_hash:requestHash,resource_type:"eu_releases",resource_id:c.release.id,capability:"music.deliver"},409);
   const msgId=`ERN-${c.release.upc||c.release.id}-${Date.now()}`;const job=(await db("eu_jobs",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify({org_id:org.id,initiative_id:c.release.initiative_id,job_type:"music.ddex.deliver",provider:"ddex",action:"deliver",capability:"music.deliver",resource_type:"eu_releases",resource_id:c.release.id,payload:{release_id:c.release.id,recipient_dpid:safeText(body.recipient_dpid,120),recipient_name:safeText(body.recipient_name,200),endpoint:safeText(body.endpoint,1000),message_id:msgId},state:"queued",approval_id:safeText(body.approval_id,80)||null,idempotency_key:`ddex:${c.release.id}:${requestHash}`,priority:8})}))?.[0];await db(`eu_releases?id=eq.${c.release.id}`,{method:"PATCH",body:JSON.stringify({status:"delivering"})});await emitEvent({orgId:org.id,initiativeId:c.release.initiative_id,eventType:"music.ddex.queued",entityType:"eu_releases",entityId:c.release.id,actorMUid:caller.mUid,actorUserId:caller.authUserId,data:{job_id:job?.id,recipient_dpid:safeText(body.recipient_dpid,120),request_hash:requestHash},idempotencyKey:`ddex:${c.release.id}:queued:${requestHash}`});return json({ok:true,job_id:job?.id,message_id:msgId,request_hash:requestHash});
 }
 return json({error:"unknown action"},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500);}});