import Stripe from 'npm:stripe@14';
const SK=Deno.env.get('STRIPE_SK')!;const stripe=new Stripe(SK);const LIVEMODE=SK.startsWith('sk_live_');const SB=Deno.env.get('SUPABASE_URL')!;const SRV=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const RETURN='https://mcclusterishere.github.io/Lvl-3-Media/dashboard.html';
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
async function rest(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',SRV);h.set('Authorization',`Bearer ${SRV}`);if(init.body)h.set('Content-Type','application/json');const r=await fetch(`${SB}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return j({error:'POST only'},405);const auth=req.headers.get('Authorization')||'';const who=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:SRV,Authorization:auth}}).then(r=>r.ok?r.json():null);if(!who?.id)return j({error:'sign_in_first'},401);
 const org=(await rest('orgs?slug=eq.level-3-media&select=id,name,slug&limit=1'))?.[0];const mem=(await rest(`org_members?org_id=eq.${org?.id}&profile_id=eq.${who.id}&role=eq.owner&select=org_id&limit=1`))?.[0];if(!mem)return j({error:'owner_required'},403);
 const rows=await rest(`org_stripe_accounts?org_id=eq.${org.id}&livemode=eq.${LIVEMODE}&select=*&limit=1`);let account:any=rows?.[0]?.stripe_account_id?await stripe.accounts.retrieve(rows[0].stripe_account_id):await stripe.accounts.create({type:'express',country:'US',email:who.email||undefined,business_profile:{name:org.name},capabilities:{card_payments:{requested:true},transfers:{requested:true}},metadata:{mccluster_org_id:org.id,mccluster_org_slug:org.slug,app_key:'level-3-media-web'}});
 const ready=account.charges_enabled===true&&account.payouts_enabled===true&&account.details_submitted===true;const status=ready?'ready':account.requirements?.disabled_reason?'disabled':'onboarding';
 await rest('org_stripe_accounts?on_conflict=org_id,livemode',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{org_id:org.id,livemode:LIVEMODE,account_reference:'level-3-media',stripe_account_id:account.id,charges_enabled:account.charges_enabled===true,payouts_enabled:account.payouts_enabled===true,details_submitted:account.details_submitted===true,onboarding_status:status,requirements:account.requirements||{},last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()}])});
 await rest(`l3_store_settings?org_id=eq.${org.id}`,{method:'PATCH',body:JSON.stringify({connected_account_id:account.id,updated_at:new Date().toISOString()})});
 if(ready)return j({status:'ready',account:account.id});const link=await stripe.accountLinks.create({account:account.id,type:'account_onboarding',refresh_url:`${RETURN}?stripe=refresh`,return_url:`${RETURN}?stripe=return`});return j({status:'onboarding',url:link.url});
});