-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0001_crm.
-- Executable reconstruction SQL: supabase/replay_migrations/0001_crm.sql
-- Intentionally no-op in production; this version is already registered live.
