-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0003_creator_cuts.
-- Executable reconstruction SQL: supabase/replay_migrations/0003_creator_cuts.sql
-- Intentionally no-op in production; this version is already registered live.
