-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0004_print_shop.
-- Executable reconstruction SQL: supabase/replay_migrations/0004_print_shop.sql
-- Intentionally no-op in production; this version is already registered live.
