-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0006_rights_flags.
-- Executable reconstruction SQL: supabase/replay_migrations/0006_rights_flags.sql
-- Intentionally no-op in production; this version is already registered live.
