-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0007_offerings.
-- Executable reconstruction SQL: supabase/replay_migrations/0007_offerings.sql
-- Intentionally no-op in production; this version is already registered live.
