-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0008_site_requests.
-- Executable reconstruction SQL: supabase/replay_migrations/0008_site_requests.sql
-- Intentionally no-op in production; this version is already registered live.
