-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0011_activation_sprints.
-- Executable reconstruction SQL: supabase/replay_migrations/0011_activation_sprints.sql
-- Intentionally no-op in production; this version is already registered live.
