-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0018_equity_uprise_seed.
-- Executable reconstruction SQL: supabase/replay_migrations/0018_equity_uprise_seed.sql
-- Intentionally no-op in production; this version is already registered live.
