-- REPLAY_ANCHOR_ONLY
-- Production ledger anchor for 0022_inbox_outbound.
-- Executable reconstruction SQL: supabase/replay_migrations/0022_inbox_outbound.sql
-- Intentionally no-op in production; this version is already registered live.
