-- Historical production-ledger anchor for 20260913023410_mnet_global_feed_for_main_network_surfaces.
-- The original production migration was applied before canonical Git reconciliation.
-- Historical schema reconstruction is provided by the numbered replay migrations.
-- Intentionally no-op: this exact version/name file exists so Supabase Git integration
-- can reconcile the remote migration ledger without re-applying historical DDL.
