-- Recorded from production. The Social Agent migration was applied twice,
-- as 20261002183039 and again as 20261002183221; every statement is
-- "if not exists", so the second run changed nothing. This file is that
-- second run, so the repo matches production's migration list exactly.
create table if not exists public.social_agent_devices (
 id uuid primary key default gen_random_uuid(), org_id uuid not null, name text not null,
 platform text not null default 'ios', status text not null default 'offline'
 check (status in ('offline','online','paused','disabled')), capabilities jsonb not null default '[]'::jsonb,
 last_seen_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.social_agent_jobs (
 id uuid primary key default gen_random_uuid(), org_id uuid not null,
 device_id uuid references public.social_agent_devices(id) on delete set null,
 platform text not null default 'instagram', action text not null default 'publish_reel',
 state text not null default 'queued' check (state in ('draft','queued','claimed','running','succeeded','failed','cancelled')),
 media_url text, caption text not null default '', payload jsonb not null default '{}'::jsonb,
 external_id text, failure text, approved_by uuid, claimed_at timestamptz, finished_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.social_agent_events (
 id bigint generated by default as identity primary key, org_id uuid not null,
 device_id uuid references public.social_agent_devices(id) on delete set null,
 job_id uuid references public.social_agent_jobs(id) on delete cascade, kind text not null,
 detail jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists social_agent_jobs_org_state_idx on public.social_agent_jobs(org_id,state,created_at);
create index if not exists social_agent_events_job_idx on public.social_agent_events(job_id,created_at desc);
alter table public.social_agent_devices enable row level security;
alter table public.social_agent_jobs enable row level security;
alter table public.social_agent_events enable row level security;
