-- Canonicalize the production signal + lead-scoring substrate that previously
-- existed live without a replayable repository migration.

create table if not exists public.ops_signals (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade,
  company_id uuid references public.out_companies(id) on delete cascade,
  contact_id uuid references public.out_contacts(id) on delete cascade,
  campaign_id uuid references public.out_campaigns(id) on delete cascade,
  signal_type text not null,
  source text not null,
  source_ref text,
  severity integer not null default 50,
  confidence numeric not null default 0.5000,
  payload jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists ops_signals_company_observed_idx
  on public.ops_signals(company_id, observed_at desc);
create index if not exists ops_signals_type_observed_idx
  on public.ops_signals(signal_type, observed_at desc);

alter table public.ops_signals enable row level security;

create table if not exists public.ops_lead_scores (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.orgs(id) on delete cascade,
  company_id uuid not null references public.out_companies(id) on delete cascade,
  score numeric not null default 0,
  engagement_score numeric not null default 0,
  urgency_score numeric not null default 0,
  fit_score numeric not null default 0,
  momentum_score numeric not null default 0,
  rationale jsonb not null default '{}'::jsonb,
  model_version text not null default 'rules-v1',
  computed_at timestamptz not null default now(),
  unique (org_id, company_id)
);

alter table public.ops_lead_scores enable row level security;

create or replace function public.ops_recompute_lead_scores(p_org_id uuid default null)
returns integer
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_count integer := 0;
begin
  with company_metrics as (
    select
      co.org_id,
      co.id as company_id,
      greatest(0, least(100,
        50 + coalesce(sum(case
          when e.type in ('reply','meeting','positive_reply','clicked') then 10
          when e.type in ('open','opened') then 3
          when e.type in ('bounce','bounced','complaint','unsubscribe') then -15
          else 0 end),0)
      ))::numeric(7,2) as engagement_score,
      greatest(0, least(100,
        coalesce(max(s.severity * s.confidence) filter (where s.observed_at >= now() - interval '30 days'), 35)
      ))::numeric(7,2) as urgency_score,
      50::numeric(7,2) as fit_score,
      greatest(0, least(100,
        30 + 8 * coalesce(count(s.id) filter (where s.observed_at >= now() - interval '14 days'),0)
      ))::numeric(7,2) as momentum_score,
      count(s.id) filter (where s.observed_at >= now() - interval '30 days') as recent_signal_count
    from public.out_companies co
    left join public.out_contacts ct on ct.company_id = co.id and ct.org_id = co.org_id
    left join public.out_events e on e.org_id = co.org_id and lower(e.address) = lower(ct.email) and e.at >= now() - interval '90 days'
    left join public.ops_signals s on s.company_id = co.id and s.org_id = co.org_id
    where p_org_id is null or co.org_id = p_org_id
    group by co.org_id, co.id
  ), scored as (
    select *,
      round((engagement_score * 0.35 + urgency_score * 0.30 + fit_score * 0.20 + momentum_score * 0.15)::numeric,2) as total_score
    from company_metrics
  )
  insert into public.ops_lead_scores(
    org_id, company_id, score, engagement_score, urgency_score, fit_score, momentum_score, rationale, model_version, computed_at
  )
  select
    org_id, company_id, total_score, engagement_score, urgency_score, fit_score, momentum_score,
    jsonb_build_object(
      'recent_signal_count', recent_signal_count,
      'weights', jsonb_build_object('engagement',0.35,'urgency',0.30,'fit',0.20,'momentum',0.15),
      'scope_action', case when total_score >= 75 then 'expand' when total_score < 35 then 'shrink' else 'hold' end
    ),
    'rules-v1', now()
  from scored
  on conflict (org_id, company_id) do update set
    score = excluded.score,
    engagement_score = excluded.engagement_score,
    urgency_score = excluded.urgency_score,
    fit_score = excluded.fit_score,
    momentum_score = excluded.momentum_score,
    rationale = excluded.rationale,
    model_version = excluded.model_version,
    computed_at = excluded.computed_at;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.ops_recompute_lead_scores(uuid) from public, anon, authenticated;
grant execute on function public.ops_recompute_lead_scores(uuid) to service_role;

create or replace function public.ops_queue_company_rescore()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_company_id uuid;
  v_org_id uuid;
begin
  if tg_table_name = 'ops_signals' then
    v_company_id := new.company_id;
    v_org_id := new.org_id;
  elsif tg_table_name = 'out_events' then
    v_org_id := new.org_id;
    select c.company_id into v_company_id
    from public.out_contacts c
    where c.org_id = new.org_id and lower(c.email) = lower(new.address)
    order by c.created_at desc
    limit 1;
  end if;

  if v_company_id is not null and not exists (
    select 1 from public.ops_agent_jobs j
    where j.org_id = v_org_id
      and j.job_type = 'lead_rescore'
      and j.target_type = 'company'
      and j.target_id = v_company_id::text
      and j.status in ('queued','running')
  ) then
    insert into public.ops_agent_jobs(org_id, job_type, target_type, target_id, priority, input)
    values(
      v_org_id, 'lead_rescore', 'company', v_company_id::text, 90,
      jsonb_build_object('trigger', tg_table_name, 'triggered_at', now())
    );
  end if;

  return new;
end;
$$;

revoke all on function public.ops_queue_company_rescore() from public, anon, authenticated;

drop trigger if exists trg_ops_signal_rescore on public.ops_signals;
create trigger trg_ops_signal_rescore
after insert on public.ops_signals
for each row execute function public.ops_queue_company_rescore();

drop trigger if exists trg_out_event_rescore on public.out_events;
create trigger trg_out_event_rescore
after insert on public.out_events
for each row execute function public.ops_queue_company_rescore();

create or replace function public.ops_maintenance_tick()
returns void
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_org uuid;
begin
  for v_org in select distinct org_id from public.out_companies loop
    perform public.ops_recompute_lead_scores(v_org);
  end loop;
end;
$$;

revoke all on function public.ops_maintenance_tick() from public, anon, authenticated;
grant execute on function public.ops_maintenance_tick() to service_role;
