(() => {
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const API_BASE=(new URLSearchParams(location.search).get('api')||localStorage.getItem('we-api-base')||'https://api.mccluster.org').replace(/\/$/,'');
  const SESSION_KEY='we-driver-session';let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');
  const state={driver:null,online:false,current:'offline',offer:null,ride:null,map:null,car:null,pickup:null,dropoff:null,route:null,offerTimer:null,pollTimer:null,geoTimer:null,shiftStarted:null,completed:Number(localStorage.getItem('we-driver-completed')||0),earnings:Number(localStorage.getItem('we-driver-earnings')||0)};
  const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(c)||0)/100);
  async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;const res=await fetch(`${API_BASE}${path}`,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||data.error||`HTTP ${res.status}`);return data}
  function setConnection(kind,label){const el=$('#connectionPill');el.className=`connection-pill ${kind}`;$('small',el).textContent=label}
  function show(name){state.current=name;$$('.state').forEach(x=>x.classList.remove('active'));$(`#${name}State`)?.classList.add('active');$('#driverSheet').scrollTop=0}
  function initMap(){if(!window.L)return;const start=[40.7414,-73.9896];state.map=L.map('map',{zoomControl:false}).setView(start,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(state.map);const icon=L.divIcon({className:'',html:'<div class="driver-pin"></div>',iconSize:[24,14],iconAnchor:[12,7]});state.car=L.marker(start,{icon}).addTo(state.map)}
  function marker(kind,latlng){const icon=L.divIcon({className:'',html:`<div class="${kind}-pin"></div>`,iconSize:[22,22],iconAnchor:[11,11]});return L.marker(latlng,{icon}).addTo(state.map)}
  function drawRide(ride){if(!state.map)return;const base=state.car?.getLatLng()||L.latLng(40.7414,-73.9896),pickup=L.latLng(ride.pickup_lat||base.lat+.008,ride.pickup_lng||base.lng+.006),drop=L.latLng(ride.dropoff_lat||pickup.lat+.025,ride.dropoff_lng||pickup.lng+.027);if(state.pickup)state.map.removeLayer(state.pickup);if(state.dropoff)state.map.removeLayer(state.dropoff);state.pickup=marker('pickup',pickup);state.dropoff=marker('dropoff',drop);if(state.route)state.map.removeLayer(state.route);state.route=L.polyline([base,pickup,drop],{color:'#F04449',weight:5,opacity:.9}).addTo(state.map);state.map.fitBounds(state.route.getBounds().pad(.25))}
  function updateStats(){$('#todayEarnings').textContent=money(Math.round(state.earnings*100));$('#completedCount').textContent=state.completed}
  function tickShift(){if(!state.shiftStarted)return;const s=Math.floor((Date.now()-state.shiftStarted)/1000);$('#shiftTime').textContent=`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}`}
  async function health(){try{await api('/health');setConnection('ok','connected');return true}catch{setConnection('bad','offline');return false}}
  function modal(id,html){let m=$('#'+id);if(m)m.remove();m=document.createElement('div');m.id=id;m.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.72);display:grid;place-items:end center;padding:16px;backdrop-filter:blur(9px)';m.innerHTML=`<div style="width:min(540px,100%);background:#101010;color:white;border:1px solid #333;border-radius:28px;padding:25px">${html}</div>`;document.body.appendChild(m);return m}
  async function ensureAuth(){if(session?.access_token){try{await api('/api/auth/me');return true}catch{session=null;localStorage.removeItem(SESSION_KEY)}}const m=modal('driverAuth',`<div style="display:flex;gap:12px;align-items:center"><img src="assets/we-icon.svg" style="width:48px;height:48px"><div><strong style="font-size:22px">WE Driver</strong><small style="display:block;color:#aaa">Sign in before going online</small></div></div><div style="display:flex;background:#222;padding:4px;border-radius:12px;margin:18px 0"><button data-auth="login" style="flex:1;padding:10px;border:0;border-radius:9px;background:#fff;font-weight:800">Sign in</button><button data-auth="signup" style="flex:1;padding:10px;border:0;background:transparent;color:#fff;font-weight:800">Create account</button></div><form id="driverAuthForm" style="display:grid;gap:12px"><input id="driverEmail" type="email" required placeholder="Email" style="padding:15px;border:1px solid #444;background:#181818;color:#fff;border-radius:13px"><input id="driverPassword" type="password" minlength="8" required placeholder="Password" style="padding:15px;border:1px solid #444;background:#181818;color:#fff;border-radius:13px"><button style="padding:15px;border:0;border-radius:13px;background:linear-gradient(135deg,#F6AD62,#F04449);color:#fff;font-weight:900">Continue</button><small id="driverAuthError" style="color:#ff8f8f"></small></form>`);let mode='login';$$('[data-auth]',m).forEach(b=>b.onclick=()=>{mode=b.dataset.auth;$$('[data-auth]',m).forEach(x=>{x.style.background=x===b?'#fff':'transparent';x.style.color=x===b?'#000':'#fff'})});$('#driverAuthForm',m).onsubmit=async e=>{e.preventDefault();try{const data=await api(mode==='login'?'/api/auth/login':'/api/auth/signup',{method:'POST',body:JSON.stringify({email:$('#driverEmail',m).value,password:$('#driverPassword',m).value,data:{product:'driver'}})});if(data.access_token){session={access_token:data.access_token,refresh_token:data.refresh_token,user:data.user};localStorage.setItem(SESSION_KEY,JSON.stringify(session));m.remove();await ensureDriver()}else $('#driverAuthError',m).textContent='Account created. Confirm your email if required, then sign in.'}catch(err){$('#driverAuthError',m).textContent=err.message}};return false}
  async function ensureDriver(){if(!session?.access_token)return false;try{const data=await api('/api/drivers/me');if(data.driver){state.driver=data.driver;return true}}catch(e){if(!/profile required/i.test(e.message))console.warn(e)}const m=modal('driverProfile',`<span style="font-size:11px;font-weight:900;letter-spacing:.12em;color:#F6AD62">DRIVER PROFILE</span><h2 style="margin:7px 0">Put your vehicle on WE.</h2><p style="color:#aaa">This driver identity is permanently tied to your signed-in account. No shared demo driver IDs.</p><form id="driverProfileForm" style="display:grid;gap:11px"><input id="displayName" required placeholder="Display name" style="padding:14px;border:1px solid #444;background:#181818;color:#fff;border-radius:12px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><input id="vehicleMake" required placeholder="Make" style="padding:14px;border:1px solid #444;background:#181818;color:#fff;border-radius:12px"><input id="vehicleModel" required placeholder="Model" style="padding:14px;border:1px solid #444;background:#181818;color:#fff;border-radius:12px"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><input id="vehicleColor" required placeholder="Color" style="padding:14px;border:1px solid #444;background:#181818;color:#fff;border-radius:12px"><input id="plate" required placeholder="License plate" style="padding:14px;border:1px solid #444;background:#181818;color:#fff;border-radius:12px"></div><button style="padding:15px;border:0;border-radius:13px;background:linear-gradient(135deg,#F6AD62,#F04449);color:#fff;font-weight:900">Create driver profile</button><small id="profileError" style="color:#ff8f8f"></small></form>`);$('#driverProfileForm',m).onsubmit=async e=>{e.preventDefault();try{const data=await api('/api/drivers/me',{method:'POST',body:JSON.stringify({tenant_slug:'whip-equipped',display_name:$('#displayName',m).value,vehicle_make:$('#vehicleMake',m).value,vehicle_model:$('#vehicleModel',m).value,vehicle_color:$('#vehicleColor',m).value,license_plate:$('#plate',m).value,seats:4})});state.driver=data.driver;m.remove();await recoverActive()}catch(err){$('#profileError',m).textContent=err.message}};return false}
  async function presence(online){if(!state.driver)return;try{const pos=await getPosition(false);const data=await api(`/api/drivers/${state.driver.id}/presence`,{method:'PATCH',body:JSON.stringify({online,lat:pos?.lat,lng:pos?.lng,heading:pos?.heading})});if(data.driver)state.driver=data.driver}catch(e){console.warn(e)}}
  function getPosition(requireAccuracy=false){return new Promise(resolve=>{if(!navigator.geolocation){resolve(null);return}navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,heading:p.coords.heading}),()=>resolve(null),{enableHighAccuracy:requireAccuracy,timeout:5000,maximumAge:5000})})}
  async function sendLocation(){const pos=await getPosition(false);if(!pos)return;state.car?.setLatLng([pos.lat,pos.lng]);if(state.online)await presence(true)}
  async function pollOffers(){if(!state.online||state.ride||state.current==='offer')return;try{const data=await api('/api/offers'),offer=data.offers?.[0];setConnection('ok','connected');if(offer){state.offer=offer;renderOffer(offer);show('offer');startOfferTimer()}}catch(e){setConnection('bad','retrying')}}
  function renderOffer(r){$('#offerFare').textContent=money(r.fare_cents);$('#offerRider').textContent=r.rider_name||'Rider';$('#offerTier').textContent=r.ride_tier;$('#offerPickup').textContent=r.pickup_label;$('#offerDropoff').textContent=r.dropoff_label;$('#pickupMeta').textContent='pickup';$('#dropoffMeta').textContent=`${Number(r.miles||0).toFixed(1)} mi · ${r.minutes||'—'} min`;drawRide(r)}
  function startOfferTimer(){clearInterval(state.offerTimer);let t=20;$('#offerTimer').textContent=`${t}s`;state.offerTimer=setInterval(()=>{t--;$('#offerTimer').textContent=`${t}s`;if(t<=0){clearInterval(state.offerTimer);state.offer=null;show('online')}},1000)}
  async function acceptOffer(){if(!state.offer||!state.driver)return;try{const data=await api(`/api/rides/${state.offer.id}/accept`,{method:'POST',body:JSON.stringify({driver_id:state.driver.id})});clearInterval(state.offerTimer);state.ride=data.ride;await setRideStatus('DRIVER_EN_ROUTE');renderActive();show('enroute')}catch(e){alert(e.message);state.offer=null;show('online')}}
  async function setRideStatus(status){if(!state.ride||!state.driver)return;const data=await api(`/api/rides/${state.ride.id}/status`,{method:'PATCH',body:JSON.stringify({driver_id:state.driver.id,status})});state.ride=data.ride;return data.ride}
  function renderActive(){const r=state.ride;if(!r)return;$('#enrouteRider').textContent=r.rider_name||'Rider';$('#enrouteRideType').textContent=r.ride_tier;$('#enroutePickup').textContent=r.pickup_label;$('#verifiedDropoff').textContent=r.dropoff_label;$('#navDestination').textContent=r.dropoff_label;$('#navEta').textContent=`${r.minutes||14} min`;$('#progressTier').textContent=r.ride_tier;$('#progressFare').textContent=money(r.fare_cents);$('#progressRider').textContent=r.rider_name||'Rider';drawRide(r)}
  async function recoverActive(){if(!state.driver)return;try{const data=await api(`/api/drivers/${state.driver.id}/active`);if(!data.ride)return;state.ride=data.ride;state.online=true;renderActive();const map={ACCEPTED:'enroute',DRIVER_EN_ROUTE:'enroute',DRIVER_ARRIVED:'arrived',VERIFIED:'verified',IN_PROGRESS:'inprogress'};show(map[state.ride.status]||'online')}catch(e){console.warn(e)}}
  async function goOnline(){if(!(await ensureAuth()))return;if(!(await ensureDriver()))return;state.online=true;state.shiftStarted=state.shiftStarted||Date.now();await presence(true);show('online');startLoops()}
  async function goOffline(){if(state.ride){alert('Finish or cancel the active ride before going offline.');return}state.online=false;await presence(false);stopLoops();show('offline')}
  function startLoops(){clearInterval(state.pollTimer);clearInterval(state.geoTimer);state.pollTimer=setInterval(pollOffers,2200);state.geoTimer=setInterval(sendLocation,10000);pollOffers()}
  function stopLoops(){clearInterval(state.pollTimer);clearInterval(state.geoTimer)}
  async function arrived(){try{await setRideStatus('DRIVER_ARRIVED');show('arrived');$('#pinInput').focus()}catch(e){alert(e.message)}}
  async function verify(){const pin=$('#pinInput').value.trim();if(pin!==String(state.ride?.pickup_pin||'')){$('#pinError').textContent='That code does not match the rider’s pickup code.';return}$('#pinError').textContent='';try{await setRideStatus('VERIFIED');show('verified')}catch(e){alert(e.message)}}
  async function startTrip(){try{await setRideStatus('IN_PROGRESS');show('inprogress')}catch(e){alert(e.message)}}
  async function complete(){try{await setRideStatus('COMPLETED');const r=state.ride,platform=r.platform_fee_cents||0,net=(r.fare_cents||0)-platform;$('#completeFare').textContent=money(r.fare_cents);$('#completePlatform').textContent=money(platform);$('#completeNet').textContent=money(net);state.completed++;state.earnings+=net/100;localStorage.setItem('we-driver-completed',state.completed);localStorage.setItem('we-driver-earnings',state.earnings);updateStats();show('complete')}catch(e){alert(e.message)}}
  function backOnline(){state.ride=null;state.offer=null;$('#pinInput').value='';show('online');pollOffers()}
  function bind(){$('#goOnline').onclick=goOnline;$('#goOffline').onclick=goOffline;$('#declineOffer').onclick=()=>{clearInterval(state.offerTimer);state.offer=null;show('online');setTimeout(pollOffers,1500)};$('#acceptOffer').onclick=acceptOffer;$('#arrivedButton').onclick=arrived;$('#verifyButton').onclick=verify;$('#startTrip').onclick=startTrip;$('#completeTrip').onclick=complete;$('#backOnline').onclick=backOnline;$('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')verify()})}
  document.addEventListener('DOMContentLoaded',async()=>{initMap();bind();updateStats();setInterval(tickShift,1000);const ok=await health();if(ok&&session?.access_token&&await ensureDriver())await recoverActive();if(state.online)startLoops();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
})();